"use client";

import type { TopicMeta } from "@/lib/types";
import ApplicationLayout from "@/components/application/ApplicationLayout";
import ApplicationHero from "@/components/application/ApplicationHero";
import ApplicationProblem from "@/components/application/ApplicationProblem";
import ApplicationMechanism from "@/components/application/ApplicationMechanism";
import Beat from "@/components/application/Beat";
import ApplicationMetrics from "@/components/application/ApplicationMetrics";
import Metric from "@/components/application/Metric";
import ApplicationCounterfactual from "@/components/application/ApplicationCounterfactual";

export const metadata: TopicMeta = {
  slug: "hallucination-in-legal-research",
  title: "Hallucination in Legal Research",
  titleVi: "Ảo giác AI trong Nghiên cứu Pháp lý",
  description:
    "Vụ Mata v. Avianca: luật sư trích dẫn 6 án lệ giả do ChatGPT bịa ra, bị tòa phạt 5.000 đô-la Mỹ",
  category: "llm-concepts",
  tags: ["hallucination", "legal", "application"],
  difficulty: "beginner",
  relatedSlugs: ["hallucination"],
  vizType: "static",
  applicationOf: "hallucination",
  featuredApp: {
    name: "ChatGPT",
    productFeature: "Legal Research (misuse case)",
    company: "OpenAI",
    countryOrigin: "US",
  },
  sources: [
    {
      title:
        "New York Lawyer Who Cited Non-Existent Cases Generated by ChatGPT Now Faces Sanctions Hearing",
      publisher: "Hinshaw & Culbertson LLP",
      url: "https://www.hinshawlaw.com/en/insights/lawyers-for-the-profession-alert/new-york-lawyer-who-cited-non-existent-cases-generated-by-chatgpt-now-faces-sanctions-hearing",
      date: "2023-06",
      kind: "news",
    },
    {
      title: "Lawyer apologizes for fake court citations from ChatGPT",
      publisher: "CNN Business",
      url: "https://www.cnn.com/2023/05/27/business/chat-gpt-avianca-mata-lawyers",
      date: "2023-05",
      kind: "news",
    },
    {
      title:
        "Mata v. Avianca, Inc., 678 F. Supp. 3d 443 (S.D.N.Y. 2023) — Opinion and Order on Sanctions",
      publisher: "U.S. District Court, Southern District of New York",
      url: "https://law.justia.com/cases/federal/district-courts/new-york/nysdce/1:2022cv01461/575368/54/",
      date: "2023-06",
      kind: "documentation",
    },
    {
      title:
        "In Landmark Case Involving Attorneys Who Submitted Fake Court Decisions Generated by ChatGPT",
      publisher: "Condon & Forsyth LLP",
      url: "https://condonlaw.com/2023/06/in-landmark-case-involving-attorneys-who-submitted-fake-court-decisions-generated-by-chatgpt-federal-judge-sanctions-the-attorneys-and-dismisses-action-as-time-barred-under-the-montreal-convention/",
      date: "2023-06",
      kind: "news",
    },
  ],
  tocSections: [
    { id: "hero", labelVi: "Công ty nào?" },
    { id: "problem", labelVi: "Vấn đề" },
    { id: "mechanism", labelVi: "Cách giải quyết" },
    { id: "metrics", labelVi: "Con số thật" },
    { id: "counterfactual", labelVi: "Nếu không có" },
  ],
};

export default function HallucinationInLegalResearch() {
  return (
    <ApplicationLayout
      metadata={metadata}
      parentTitleVi="Ảo giác AI"
    >
      <ApplicationHero
        parentTitleVi="Ảo giác AI"
        topicSlug="hallucination-in-legal-research"
      >
        <p>
          Tháng 3 năm 2023, luật sư Steven Schwartz &mdash; người đã hành nghề
          hơn 30 năm tại New York &mdash; nộp một bản kiến nghị pháp lý cho Tòa
          án Liên bang Quận Nam New York (U.S. District Court, Southern District
          of New York) trong vụ Mata v. Avianca (vụ kiện tại tòa liên bang).
        </p>
        <p>
          Bản kiến nghị trích dẫn sáu vụ án tiền lệ (precedent &mdash; phán
          quyết trước đó được dùng làm căn cứ pháp lý) để bảo vệ thân chủ.
          Vấn đề: cả sáu vụ án đều không tồn tại. Chúng được ChatGPT (trợ lý
          trò chuyện của OpenAI) bịa ra hoàn toàn &mdash; với tên vụ án, số hiệu
          trích dẫn, và cả trích dẫn giả từ các thẩm phán giả.
        </p>
      </ApplicationHero>

      <ApplicationProblem topicSlug="hallucination-in-legal-research">
        <p>
          &ldquo;Ảo giác&rdquo; (hallucination) là hiện tượng mô hình ngôn ngữ
          lớn (LLM &mdash; Large Language Model) tạo ra thông tin có vẻ chính
          xác nhưng hoàn toàn bịa đặt.
        </p>
        <p>
          Trong lĩnh vực pháp lý, mỗi trích dẫn án lệ phải dẫn đến một bản
          án thực sự &mdash; có thẩm phán thực, tòa án thực, và phán quyết
          thực &mdash; vì luật sư và thẩm phán dựa vào đó để ra quyết định
          ảnh hưởng đến quyền lợi con người.
        </p>
        <p>
          Khi AI bịa ra các vụ án nghe rất thuyết phục nhưng không hề có thật,
          nó phá vỡ nền tảng tin cậy của hệ thống tư pháp (judicial system
          &mdash; hệ thống các tòa án xét xử).
        </p>
      </ApplicationProblem>

      <ApplicationMechanism
        parentTitleVi="Ảo giác AI"
        topicSlug="hallucination-in-legal-research"
      >
        <Beat step={1}>
          <p>
            <strong>Sử dụng ChatGPT để nghiên cứu pháp lý.</strong> Luật sư
            Steven Schwartz thuộc hãng Levidow, Levidow &amp; Oberman sử dụng
            ChatGPT để tìm án lệ liên quan đến vụ kiện thương tích cá nhân
            (personal injury &mdash; vụ kiện đòi bồi thường tổn hại sức khỏe)
            của thân chủ Roberto Mata chống hãng hàng không Avianca. Schwartz
            chưa từng dùng ChatGPT cho nghiên cứu pháp lý trước đó.
          </p>
        </Beat>
        <Beat step={2}>
          <p>
            <strong>ChatGPT bịa ra sáu án lệ.</strong> ChatGPT tạo ra sáu
            trích dẫn án lệ bịa đặt, gồm Varghese v. China Southern Airlines,
            Martinez v. Delta Airlines, Miller v. United Airlines &mdash; với
            đầy đủ số hiệu, tên tòa, năm phán quyết. Khi Schwartz hỏi xác
            nhận, ChatGPT khẳng định các vụ án &ldquo;tồn tại trên
            LexisNexis và Westlaw&rdquo; (hai cơ sở dữ liệu pháp lý chính
            thức tại Mỹ).
          </p>
        </Beat>
        <Beat step={3}>
          <p>
            <strong>Tòa phát hiện gian lận.</strong> Luật sư của Avianca không
            tìm thấy bất kỳ vụ án nào trong cơ sở dữ liệu pháp lý và thông
            báo cho tòa. Thẩm phán P. Kevin Castel yêu cầu nộp bản sao các
            bản án. Tòa phát hiện tất cả là &ldquo;các quyết định tư pháp giả
            với trích dẫn giả và nội dung giả&rdquo;.
          </p>
        </Beat>
        <Beat step={4}>
          <p>
            <strong>Xử phạt theo Quy tắc 11.</strong> Ngày 22 tháng 6 năm
            2023, Thẩm phán Castel ban hành lệnh xử phạt theo Rule 11 (Quy
            tắc 11 &mdash; quy tắc liên bang yêu cầu luật sư xác minh tính
            chính xác của mọi hồ sơ trước khi nộp). Tòa phạt Peter LoDuca,
            Steven Schwartz, và hãng luật 5.000 đô-la Mỹ. Tòa kết luận
            các luật sư hành động với &ldquo;thiếu thiện chí chủ
            quan&rdquo; (subjective bad faith). Các luật sư bị yêu cầu
            gửi thư xin lỗi đến thẩm phán bị gán tên sai.
          </p>
        </Beat>
      </ApplicationMechanism>

      <ApplicationMetrics
        sources={metadata.sources!}
        topicSlug="hallucination-in-legal-research"
      >
        <Metric
          value="6 vụ án giả được trích dẫn trong bản kiến nghị"
          sourceRef={2}
        />
        <Metric
          value="5.000 đô-la Mỹ tiền phạt theo Quy tắc 11"
          sourceRef={3}
        />
        <Metric
          value="Hơn 30 năm kinh nghiệm hành nghề của luật sư vẫn không phát hiện ảo giác"
          sourceRef={2}
        />
      </ApplicationMetrics>

      <ApplicationCounterfactual
        parentTitleVi="Ảo giác AI"
        topicSlug="hallucination-in-legal-research"
      >
        <p>
          Nếu mô hình ngôn ngữ lớn không có hiện tượng ảo giác, ChatGPT sẽ chỉ
          trả về các án lệ thực sự tồn tại, hoặc thông báo rõ ràng rằng không
          tìm thấy án lệ phù hợp.
        </p>
        <p>
          Tuy nhiên, ngay cả khi AI chính xác hơn trong tương lai, nghĩa vụ
          kiểm chứng (duty to verify &mdash; trách nhiệm xác minh thông tin)
          của luật sư vẫn là nguyên tắc cốt lõi của đạo đức nghề nghiệp.
        </p>
      </ApplicationCounterfactual>
    </ApplicationLayout>
  );
}
