import type { TopicMeta, Category } from "@/lib/types";

// ─────────────────────────────────────────────────────────
// 17 Categories
// ─────────────────────────────────────────────────────────

export const categories: Category[] = [
  {
    slug: "neural-fundamentals",
    nameVi: "Nền tảng mạng nơ-ron",
    icon: "brain",
    description: "Các khái niệm nền tảng về mạng nơ-ron nhân tạo",
  },
  {
    slug: "classic-ml",
    nameVi: "Thuật toán ML cổ điển",
    icon: "bar-chart-2",
    description: "Các thuật toán học máy truyền thống và phổ biến",
  },
  {
    slug: "dl-architectures",
    nameVi: "Kiến trúc Deep Learning",
    icon: "layers",
    description: "Các kiến trúc học sâu tiên tiến",
  },
  {
    slug: "nlp",
    nameVi: "Xử lý ngôn ngữ tự nhiên",
    icon: "message-square",
    description: "Các kỹ thuật xử lý và hiểu ngôn ngữ tự nhiên",
  },
  {
    slug: "computer-vision",
    nameVi: "Thị giác máy tính",
    icon: "eye",
    description: "Các phương pháp giúp máy tính hiểu hình ảnh và video",
  },
  {
    slug: "search-retrieval",
    nameVi: "Tìm kiếm & Truy xuất",
    icon: "search",
    description: "Các kỹ thuật tìm kiếm và truy xuất thông tin",
  },
  {
    slug: "llm-concepts",
    nameVi: "Khái niệm LLM",
    icon: "bot",
    description: "Các khái niệm cốt lõi về mô hình ngôn ngữ lớn",
  },
  {
    slug: "training-optimization",
    nameVi: "Huấn luyện & Tối ưu",
    icon: "settings",
    description: "Các phương pháp huấn luyện và tối ưu hoá mô hình",
  },
  {
    slug: "ai-agents",
    nameVi: "AI Agent & Công cụ",
    icon: "cpu",
    description: "Kiến trúc và công cụ xây dựng AI Agent",
  },
  {
    slug: "multimodal",
    nameVi: "AI Đa phương thức",
    icon: "image",
    description: "Mô hình AI xử lý nhiều dạng dữ liệu khác nhau",
  },
  {
    slug: "ai-safety",
    nameVi: "An toàn & Đạo đức AI",
    icon: "shield",
    description: "Các vấn đề an toàn, công bằng và đạo đức trong AI",
  },
  {
    slug: "infrastructure",
    nameVi: "Hạ tầng & Triển khai",
    icon: "server",
    description: "Hạ tầng kỹ thuật để triển khai và vận hành mô hình AI",
  },
  {
    slug: "emerging",
    nameVi: "Xu hướng mới 2025-2026",
    icon: "trending-up",
    description: "Các xu hướng và công nghệ AI mới nổi",
  },
  {
    slug: "foundations",
    nameVi: "Khái niệm cơ sở",
    icon: "book-open",
    description: "Các khái niệm cơ bản trong học máy và khoa học dữ liệu",
  },
  {
    slug: "reinforcement-learning",
    nameVi: "Học tăng cường",
    icon: "gamepad-2",
    description: "Các thuật toán học từ phần thưởng và tương tác với môi trường",
  },
  {
    slug: "applied-ai",
    nameVi: "Ứng dụng AI thực tế",
    icon: "briefcase",
    description: "Ứng dụng thực tiễn của AI trong các lĩnh vực khác nhau",
  },
  {
    slug: "math-foundations",
    nameVi: "Nền tảng toán học cho AI",
    icon: "calculator",
    description: "Các kiến thức toán học cần thiết để hiểu sâu AI/ML",
  },
];

// ─────────────────────────────────────────────────────────
// 185 Topics — Full Metadata
// ─────────────────────────────────────────────────────────

export const topicList: TopicMeta[] = [
  // ═══════════════════════════════════════════════════════
  // Category 1: neural-fundamentals (16 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "perceptron",
    title: "Perceptron",
    titleVi: "Perceptron",
    description: "Đơn vị tính toán cơ bản nhất của mạng nơ-ron, mô phỏng một nơ-ron đơn lẻ",
    category: "neural-fundamentals",
    tags: ["neuron", "weights", "bias"],
    difficulty: "beginner",
    relatedSlugs: ["mlp", "activation-functions", "forward-propagation"],
    vizType: "interactive",
  },
  {
    slug: "mlp",
    title: "Multilayer Perceptron",
    titleVi: "Perceptron đa tầng",
    description: "Mạng nơ-ron nhiều lớp có khả năng học các mối quan hệ phi tuyến phức tạp",
    category: "neural-fundamentals",
    tags: ["neural-network", "layers", "deep-learning"],
    difficulty: "beginner",
    relatedSlugs: ["perceptron", "activation-functions", "backpropagation"],
    vizType: "interactive",
  },
  {
    slug: "activation-functions",
    title: "Activation Functions",
    titleVi: "Hàm kích hoạt",
    description: "Các hàm phi tuyến (Sigmoid, ReLU, Tanh) giúp mạng nơ-ron học được các mẫu phức tạp",
    category: "neural-fundamentals",
    tags: ["sigmoid", "relu", "tanh"],
    difficulty: "beginner",
    relatedSlugs: ["perceptron", "mlp", "vanishing-exploding-gradients"],
    vizType: "interactive",
  },
  {
    slug: "forward-propagation",
    title: "Forward Propagation",
    titleVi: "Lan truyền xuôi",
    description: "Quá trình truyền dữ liệu qua các lớp mạng nơ-ron từ đầu vào đến đầu ra",
    category: "neural-fundamentals",
    tags: ["inference", "computation", "layers"],
    difficulty: "beginner",
    relatedSlugs: ["backpropagation", "mlp", "activation-functions"],
    vizType: "interactive",
  },
  {
    slug: "backpropagation",
    title: "Backpropagation",
    titleVi: "Lan truyền ngược",
    description: "Thuật toán tính gradient lỗi và lan truyền ngược để cập nhật trọng số",
    category: "neural-fundamentals",
    tags: ["gradient", "training", "chain-rule"],
    difficulty: "intermediate",
    relatedSlugs: ["forward-propagation", "gradient-descent", "loss-functions"],
    vizType: "interactive",
  },
  {
    slug: "gradient-descent",
    title: "Gradient Descent",
    titleVi: "Hạ gradient",
    description: "Thuật toán tối ưu cốt lõi, tìm cực tiểu hàm mất mát bằng cách đi theo hướng gradient",
    category: "neural-fundamentals",
    tags: ["optimization", "training", "convergence"],
    difficulty: "beginner",
    relatedSlugs: ["sgd", "learning-rate", "loss-functions", "optimizers"],
    vizType: "interactive",
  },
  {
    slug: "sgd",
    title: "Stochastic Gradient Descent",
    titleVi: "Hạ gradient ngẫu nhiên",
    description: "Biến thể của hạ gradient sử dụng từng mẫu hoặc mini-batch để cập nhật nhanh hơn",
    category: "neural-fundamentals",
    tags: ["optimization", "mini-batch", "stochastic"],
    difficulty: "intermediate",
    relatedSlugs: ["gradient-descent", "optimizers", "learning-rate", "epochs-batches"],
    vizType: "interactive",
  },
  {
    slug: "learning-rate",
    title: "Learning Rate",
    titleVi: "Tốc độ học",
    description: "Siêu tham số quan trọng quyết định bước nhảy khi cập nhật trọng số mô hình",
    category: "neural-fundamentals",
    tags: ["hyperparameter", "training", "convergence"],
    difficulty: "beginner",
    relatedSlugs: ["gradient-descent", "sgd", "optimizers"],
    vizType: "interactive",
  },
  {
    slug: "loss-functions",
    title: "Loss Functions",
    titleVi: "Hàm mất mát",
    description: "Hàm đo lường sai số giữa dự đoán của mô hình và giá trị thực tế",
    category: "neural-fundamentals",
    tags: ["mse", "cross-entropy", "training"],
    difficulty: "beginner",
    relatedSlugs: ["gradient-descent", "backpropagation", "overfitting-underfitting"],
    vizType: "interactive",
  },
  {
    slug: "overfitting-underfitting",
    title: "Overfitting & Underfitting",
    titleVi: "Quá khớp & Dưới khớp",
    description: "Hai vấn đề phổ biến khi mô hình học quá nhiều hoặc quá ít từ dữ liệu",
    category: "neural-fundamentals",
    tags: ["generalization", "model-complexity", "validation"],
    difficulty: "beginner",
    relatedSlugs: ["regularization", "bias-variance", "cross-validation"],
    vizType: "interactive",
  },
  {
    slug: "regularization",
    title: "Regularization",
    titleVi: "Chính quy hoá",
    description: "Kỹ thuật (L1, L2, Dropout) ngăn mô hình quá khớp bằng cách phạt độ phức tạp",
    category: "neural-fundamentals",
    tags: ["l1", "l2", "dropout"],
    difficulty: "intermediate",
    relatedSlugs: ["overfitting-underfitting", "loss-functions", "batch-normalization"],
    vizType: "interactive",
  },
  {
    slug: "batch-normalization",
    title: "Batch Normalization",
    titleVi: "Chuẩn hoá batch",
    description: "Kỹ thuật chuẩn hoá đầu vào của mỗi lớp để huấn luyện nhanh và ổn định hơn",
    category: "neural-fundamentals",
    tags: ["normalization", "training", "stability"],
    difficulty: "intermediate",
    relatedSlugs: ["regularization", "vanishing-exploding-gradients", "weight-initialization"],
    vizType: "static",
  },
  {
    slug: "vanishing-exploding-gradients",
    title: "Vanishing & Exploding Gradients",
    titleVi: "Gradient biến mất & bùng nổ",
    description: "Hiện tượng gradient trở nên quá nhỏ hoặc quá lớn khi lan truyền qua nhiều lớp",
    category: "neural-fundamentals",
    tags: ["gradient", "deep-networks", "stability"],
    difficulty: "intermediate",
    relatedSlugs: ["backpropagation", "activation-functions", "weight-initialization", "residual-connections"],
    vizType: "interactive",
  },
  {
    slug: "weight-initialization",
    title: "Weight Initialization",
    titleVi: "Khởi tạo trọng số",
    description: "Phương pháp gán giá trị ban đầu cho trọng số để đảm bảo quá trình huấn luyện hội tụ",
    category: "neural-fundamentals",
    tags: ["xavier", "he", "initialization"],
    difficulty: "intermediate",
    relatedSlugs: ["vanishing-exploding-gradients", "batch-normalization", "activation-functions"],
    vizType: "static",
  },
  {
    slug: "optimizers",
    title: "Optimizers",
    titleVi: "Bộ tối ưu",
    description: "Các thuật toán tối ưu nâng cao (Adam, RMSProp) giúp hội tụ nhanh và ổn định hơn SGD",
    category: "neural-fundamentals",
    tags: ["adam", "rmsprop", "momentum"],
    difficulty: "intermediate",
    relatedSlugs: ["gradient-descent", "sgd", "learning-rate"],
    vizType: "interactive",
  },
  {
    slug: "epochs-batches",
    title: "Epochs, Batches & Iterations",
    titleVi: "Epochs, Batches & Iterations",
    description: "Các khái niệm cơ bản về cách dữ liệu được chia và lặp lại trong quá trình huấn luyện",
    category: "neural-fundamentals",
    tags: ["training", "batch-size", "iterations"],
    difficulty: "beginner",
    relatedSlugs: ["sgd", "gradient-descent", "learning-rate"],
    vizType: "interactive",
  },

  // ═══════════════════════════════════════════════════════
  // Category 2: classic-ml (16 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "linear-regression",
    title: "Linear Regression",
    titleVi: "Hồi quy tuyến tính",
    description: "Thuật toán dự đoán giá trị liên tục bằng cách tìm đường thẳng phù hợp nhất với dữ liệu",
    category: "classic-ml",
    tags: ["regression", "prediction", "statistics"],
    difficulty: "beginner",
    relatedSlugs: ["polynomial-regression", "logistic-regression", "loss-functions"],
    vizType: "interactive",
  },
  {
    slug: "polynomial-regression",
    title: "Polynomial Regression",
    titleVi: "Hồi quy đa thức",
    description: "Mở rộng hồi quy tuyến tính với các bậc cao hơn để mô hình hoá quan hệ phi tuyến",
    category: "classic-ml",
    tags: ["regression", "polynomial", "curve-fitting"],
    difficulty: "beginner",
    relatedSlugs: ["linear-regression", "overfitting-underfitting", "bias-variance"],
    vizType: "interactive",
  },
  {
    slug: "logistic-regression",
    title: "Logistic Regression",
    titleVi: "Hồi quy logistic",
    description: "Thuật toán phân loại nhị phân sử dụng hàm sigmoid để dự đoán xác suất",
    category: "classic-ml",
    tags: ["classification", "sigmoid", "probability"],
    difficulty: "beginner",
    relatedSlugs: ["linear-regression", "activation-functions", "confusion-matrix"],
    vizType: "interactive",
  },
  {
    slug: "decision-trees",
    title: "Decision Trees",
    titleVi: "Cây quyết định",
    description: "Mô hình phân loại và hồi quy bằng cách chia dữ liệu theo chuỗi quyết định dạng cây",
    category: "classic-ml",
    tags: ["classification", "regression", "tree"],
    difficulty: "beginner",
    relatedSlugs: ["random-forests", "gradient-boosting", "ensemble-methods"],
    vizType: "interactive",
  },
  {
    slug: "random-forests",
    title: "Random Forests",
    titleVi: "Rừng ngẫu nhiên",
    description: "Phương pháp kết hợp nhiều cây quyết định để tăng độ chính xác và giảm quá khớp",
    category: "classic-ml",
    tags: ["ensemble", "bagging", "classification"],
    difficulty: "intermediate",
    relatedSlugs: ["decision-trees", "gradient-boosting", "ensemble-methods"],
    vizType: "interactive",
  },
  {
    slug: "gradient-boosting",
    title: "Gradient Boosting (XGBoost)",
    titleVi: "Tăng cường gradient",
    description: "Phương pháp xây dựng tuần tự các mô hình yếu để tạo mô hình mạnh (XGBoost, LightGBM)",
    category: "classic-ml",
    tags: ["boosting", "xgboost", "ensemble"],
    difficulty: "intermediate",
    relatedSlugs: ["decision-trees", "random-forests", "ensemble-methods"],
    vizType: "interactive",
  },
  {
    slug: "svm",
    title: "Support Vector Machine",
    titleVi: "Máy vector hỗ trợ",
    description: "Thuật toán tìm siêu phẳng tối ưu để phân chia dữ liệu với lề lớn nhất",
    category: "classic-ml",
    tags: ["classification", "kernel", "margin"],
    difficulty: "intermediate",
    relatedSlugs: ["logistic-regression", "knn", "linear-regression"],
    vizType: "interactive",
  },
  {
    slug: "knn",
    title: "K-Nearest Neighbors",
    titleVi: "K láng giềng gần nhất",
    description: "Thuật toán phân loại dựa trên k điểm dữ liệu gần nhất trong không gian đặc trưng",
    category: "classic-ml",
    tags: ["classification", "distance", "non-parametric"],
    difficulty: "beginner",
    relatedSlugs: ["k-means", "svm", "decision-trees"],
    vizType: "interactive",
  },
  {
    slug: "k-means",
    title: "K-Means Clustering",
    titleVi: "Phân cụm K-Means",
    description: "Thuật toán phân cụm chia dữ liệu thành K nhóm dựa trên khoảng cách đến tâm cụm",
    category: "classic-ml",
    tags: ["clustering", "unsupervised", "centroids"],
    difficulty: "beginner",
    relatedSlugs: ["dbscan", "knn", "pca"],
    vizType: "interactive",
  },
  {
    slug: "dbscan",
    title: "DBSCAN",
    titleVi: "DBSCAN",
    description: "Thuật toán phân cụm dựa trên mật độ, tự phát hiện số cụm và loại nhiễu",
    category: "classic-ml",
    tags: ["clustering", "density", "unsupervised"],
    difficulty: "intermediate",
    relatedSlugs: ["k-means", "knn", "pca"],
    vizType: "interactive",
  },
  {
    slug: "pca",
    title: "Principal Component Analysis",
    titleVi: "Phân tích thành phần chính",
    description: "Kỹ thuật giảm chiều dữ liệu bằng cách tìm các trục biến thiên lớn nhất",
    category: "classic-ml",
    tags: ["dimensionality-reduction", "unsupervised", "eigenvalues"],
    difficulty: "intermediate",
    relatedSlugs: ["t-sne", "dimensionality-curse", "feature-engineering"],
    vizType: "interactive",
  },
  {
    slug: "t-sne",
    title: "t-SNE",
    titleVi: "t-SNE",
    description: "Kỹ thuật giảm chiều phi tuyến để trực quan hoá dữ liệu đa chiều trong 2D/3D",
    category: "classic-ml",
    tags: ["visualization", "dimensionality-reduction", "embedding"],
    difficulty: "intermediate",
    relatedSlugs: ["pca", "word-embeddings", "dimensionality-curse"],
    vizType: "interactive",
  },
  {
    slug: "naive-bayes",
    title: "Naive Bayes",
    titleVi: "Naive Bayes",
    description: "Thuật toán phân loại xác suất dựa trên định lý Bayes với giả định độc lập",
    category: "classic-ml",
    tags: ["classification", "probability", "bayes"],
    difficulty: "beginner",
    relatedSlugs: ["logistic-regression", "text-classification", "sentiment-analysis"],
    vizType: "static",
  },
  {
    slug: "bias-variance",
    title: "Bias-Variance Tradeoff",
    titleVi: "Đánh đổi Bias-Variance",
    description: "Sự cân bằng giữa lỗi do đơn giản hoá mô hình (bias) và lỗi do nhạy cảm với dữ liệu (variance)",
    category: "classic-ml",
    tags: ["generalization", "model-complexity", "error"],
    difficulty: "intermediate",
    relatedSlugs: ["overfitting-underfitting", "regularization", "cross-validation"],
    vizType: "interactive",
  },
  {
    slug: "cross-validation",
    title: "Cross-Validation",
    titleVi: "Kiểm chứng chéo",
    description: "Phương pháp đánh giá mô hình bằng cách chia dữ liệu thành nhiều phần luân phiên",
    category: "classic-ml",
    tags: ["evaluation", "k-fold", "validation"],
    difficulty: "beginner",
    relatedSlugs: ["bias-variance", "overfitting-underfitting", "train-val-test"],
    vizType: "interactive",
  },
  {
    slug: "confusion-matrix",
    title: "Confusion Matrix / Precision / Recall / F1",
    titleVi: "Ma trận nhầm lẫn / Precision / Recall / F1",
    description: "Các chỉ số đánh giá hiệu suất mô hình phân loại một cách toàn diện",
    category: "classic-ml",
    tags: ["evaluation", "precision", "recall", "f1"],
    difficulty: "beginner",
    relatedSlugs: ["logistic-regression", "roc-auc", "cross-validation"],
    vizType: "interactive",
  },

  // ═══════════════════════════════════════════════════════
  // Category 3: dl-architectures (18 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "cnn",
    title: "Convolutional Neural Network",
    titleVi: "Mạng nơ-ron tích chập",
    description: "Kiến trúc mạng chuyên xử lý dữ liệu dạng lưới như hình ảnh bằng phép tích chập",
    category: "dl-architectures",
    tags: ["convolution", "image", "deep-learning"],
    difficulty: "intermediate",
    relatedSlugs: ["convolution", "pooling", "image-classification"],
    vizType: "interactive",
  },
  {
    slug: "convolution",
    title: "Convolution Operation",
    titleVi: "Phép tích chập",
    description: "Phép toán trượt bộ lọc trên dữ liệu đầu vào để trích xuất đặc trưng cục bộ",
    category: "dl-architectures",
    tags: ["kernel", "filter", "feature-extraction"],
    difficulty: "intermediate",
    relatedSlugs: ["cnn", "pooling", "image-kernels"],
    vizType: "interactive",
  },
  {
    slug: "pooling",
    title: "Pooling Layers",
    titleVi: "Lớp gộp",
    description: "Lớp giảm kích thước không gian của đặc trưng, giữ lại thông tin quan trọng nhất",
    category: "dl-architectures",
    tags: ["max-pooling", "average-pooling", "downsampling"],
    difficulty: "intermediate",
    relatedSlugs: ["cnn", "convolution", "feature-extraction-cnn"],
    vizType: "interactive",
  },
  {
    slug: "rnn",
    title: "Recurrent Neural Network",
    titleVi: "Mạng nơ-ron hồi quy",
    description: "Kiến trúc mạng xử lý dữ liệu tuần tự bằng cách duy trì trạng thái ẩn qua thời gian",
    category: "dl-architectures",
    tags: ["sequence", "temporal", "recurrent"],
    difficulty: "intermediate",
    relatedSlugs: ["lstm", "gru", "seq2seq"],
    vizType: "interactive",
  },
  {
    slug: "lstm",
    title: "Long Short-Term Memory",
    titleVi: "Bộ nhớ dài-ngắn hạn",
    description: "Biến thể RNN với cơ chế cổng giúp ghi nhớ thông tin dài hạn hiệu quả",
    category: "dl-architectures",
    tags: ["gates", "memory", "sequence"],
    difficulty: "intermediate",
    relatedSlugs: ["rnn", "gru", "vanishing-exploding-gradients"],
    vizType: "interactive",
  },
  {
    slug: "gru",
    title: "Gated Recurrent Unit",
    titleVi: "GRU",
    description: "Biến thể đơn giản hơn của LSTM với ít cổng hơn nhưng hiệu quả tương đương",
    category: "dl-architectures",
    tags: ["gates", "sequence", "simplified"],
    difficulty: "intermediate",
    relatedSlugs: ["lstm", "rnn", "seq2seq"],
    vizType: "interactive",
  },
  {
    slug: "autoencoder",
    title: "Autoencoder",
    titleVi: "Tự mã hoá",
    description: "Mạng nơ-ron học nén dữ liệu vào biểu diễn ẩn rồi tái tạo lại đầu vào",
    category: "dl-architectures",
    tags: ["encoding", "compression", "unsupervised"],
    difficulty: "intermediate",
    relatedSlugs: ["vae", "pca", "dimensionality-curse"],
    vizType: "interactive",
  },
  {
    slug: "vae",
    title: "Variational Autoencoder",
    titleVi: "Bộ tự mã hoá biến phân",
    description: "Biến thể xác suất của autoencoder cho phép sinh dữ liệu mới từ không gian ẩn",
    category: "dl-architectures",
    tags: ["generative", "latent-space", "variational"],
    difficulty: "advanced",
    relatedSlugs: ["autoencoder", "gan", "diffusion-models"],
    vizType: "interactive",
  },
  {
    slug: "gan",
    title: "Generative Adversarial Network",
    titleVi: "Mạng đối kháng sinh tạo",
    description: "Kiến trúc hai mạng đối kháng nhau — bộ sinh và bộ phân biệt — để tạo dữ liệu giả chân thực",
    category: "dl-architectures",
    tags: ["generative", "adversarial", "generator"],
    difficulty: "advanced",
    relatedSlugs: ["vae", "diffusion-models", "text-to-image"],
    vizType: "interactive",
  },
  {
    slug: "diffusion-models",
    title: "Diffusion Models",
    titleVi: "Mô hình khuếch tán",
    description: "Mô hình sinh dữ liệu bằng cách học đảo ngược quá trình thêm nhiễu dần dần",
    category: "dl-architectures",
    tags: ["generative", "denoising", "image-generation"],
    difficulty: "advanced",
    relatedSlugs: ["gan", "vae", "text-to-image"],
    vizType: "interactive",
  },
  {
    slug: "transformer",
    title: "Transformer",
    titleVi: "Kiến trúc Transformer",
    description: "Kiến trúc nền tảng dựa trên cơ chế chú ý, cốt lõi của mọi LLM hiện đại",
    category: "dl-architectures",
    tags: ["attention", "architecture", "nlp"],
    difficulty: "intermediate",
    relatedSlugs: ["self-attention", "multi-head-attention", "positional-encoding"],
    vizType: "interactive",
  },
  {
    slug: "self-attention",
    title: "Self-Attention",
    titleVi: "Tự chú ý",
    description: "Cơ chế cho phép mỗi phần tử trong chuỗi chú ý đến tất cả các phần tử khác",
    category: "dl-architectures",
    tags: ["attention", "query-key-value", "transformer"],
    difficulty: "intermediate",
    relatedSlugs: ["transformer", "multi-head-attention", "attention-mechanism"],
    vizType: "interactive",
  },
  {
    slug: "multi-head-attention",
    title: "Multi-Head Attention",
    titleVi: "Chú ý đa đầu",
    description: "Mở rộng cơ chế chú ý với nhiều đầu song song để nắm bắt nhiều mối quan hệ khác nhau",
    category: "dl-architectures",
    tags: ["attention", "parallel", "transformer"],
    difficulty: "intermediate",
    relatedSlugs: ["self-attention", "transformer", "positional-encoding"],
    vizType: "interactive",
  },
  {
    slug: "positional-encoding",
    title: "Positional Encoding",
    titleVi: "Mã hoá vị trí",
    description: "Phương pháp mã hoá thứ tự vị trí của các token bằng hàm sin/cos cho Transformer",
    category: "dl-architectures",
    tags: ["position", "sine-cosine", "transformer"],
    difficulty: "intermediate",
    relatedSlugs: ["transformer", "self-attention", "tokenization"],
    vizType: "static",
  },
  {
    slug: "residual-connections",
    title: "Residual Connections",
    titleVi: "Kết nối tắt",
    description: "Kỹ thuật kết nối tắt cho phép gradient chảy trực tiếp qua các lớp, giúp huấn luyện mạng sâu",
    category: "dl-architectures",
    tags: ["skip-connection", "deep-networks", "resnet"],
    difficulty: "intermediate",
    relatedSlugs: ["vanishing-exploding-gradients", "transformer", "batch-normalization"],
    vizType: "static",
  },
  {
    slug: "transfer-learning",
    title: "Transfer Learning",
    titleVi: "Học chuyển giao",
    description: "Kỹ thuật tận dụng mô hình đã huấn luyện trước để giải quyết bài toán mới nhanh hơn",
    category: "dl-architectures",
    tags: ["pre-trained", "fine-tuning", "features"],
    difficulty: "intermediate",
    relatedSlugs: ["fine-tuning", "bert", "cnn"],
    vizType: "static",
  },
  {
    slug: "u-net",
    title: "U-Net",
    titleVi: "U-Net",
    description: "Kiến trúc mã hoá-giải mã hình chữ U chuyên dùng cho phân đoạn ảnh y khoa",
    category: "dl-architectures",
    tags: ["segmentation", "encoder-decoder", "medical"],
    difficulty: "advanced",
    relatedSlugs: ["cnn", "semantic-segmentation", "autoencoder"],
    vizType: "static",
  },
  {
    slug: "nerf",
    title: "NeRF",
    titleVi: "NeRF",
    description: "Mô hình tái tạo cảnh 3D từ tập hợp ảnh 2D bằng trường bức xạ nơ-ron",
    category: "dl-architectures",
    tags: ["3d-reconstruction", "neural-radiance", "rendering"],
    difficulty: "advanced",
    relatedSlugs: ["cnn", "mlp", "computer-vision"],
    vizType: "static",
  },

  // ═══════════════════════════════════════════════════════
  // Category 4: nlp (15 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "tokenization",
    title: "Tokenization",
    titleVi: "Token hoá",
    description: "Quá trình chia văn bản thành các đơn vị nhỏ (token) để mô hình xử lý được",
    category: "nlp",
    tags: ["text-processing", "bpe", "subword"],
    difficulty: "beginner",
    relatedSlugs: ["word-embeddings", "bag-of-words", "bert"],
    vizType: "interactive",
  },
  {
    slug: "bag-of-words",
    title: "Bag of Words",
    titleVi: "Túi từ",
    description: "Phương pháp biểu diễn văn bản bằng tần suất xuất hiện từ, bỏ qua thứ tự",
    category: "nlp",
    tags: ["text-representation", "frequency", "simple"],
    difficulty: "beginner",
    relatedSlugs: ["tf-idf", "tokenization", "word-embeddings"],
    vizType: "interactive",
  },
  {
    slug: "tf-idf",
    title: "TF-IDF",
    titleVi: "TF-IDF",
    description: "Phương pháp đánh trọng số từ dựa trên tần suất trong văn bản và độ hiếm trong kho ngữ liệu",
    category: "nlp",
    tags: ["text-representation", "frequency", "retrieval"],
    difficulty: "beginner",
    relatedSlugs: ["bag-of-words", "bm25", "text-classification"],
    vizType: "interactive",
  },
  {
    slug: "word-embeddings",
    title: "Word Embeddings",
    titleVi: "Nhúng từ",
    description: "Biểu diễn từ dưới dạng vector số thực, nắm bắt ngữ nghĩa và quan hệ giữa các từ",
    category: "nlp",
    tags: ["vector", "semantic", "representation"],
    difficulty: "intermediate",
    relatedSlugs: ["word2vec", "glove", "tokenization", "embedding-model"],
    vizType: "interactive",
  },
  {
    slug: "word2vec",
    title: "Word2Vec",
    titleVi: "Word2Vec",
    description: "Mô hình học biểu diễn từ bằng cách dự đoán từ dựa trên ngữ cảnh xung quanh",
    category: "nlp",
    tags: ["cbow", "skip-gram", "embedding"],
    difficulty: "intermediate",
    relatedSlugs: ["word-embeddings", "glove", "tokenization"],
    vizType: "interactive",
  },
  {
    slug: "glove",
    title: "GloVe",
    titleVi: "GloVe",
    description: "Phương pháp nhúng từ dựa trên ma trận đồng xuất hiện toàn cục của từ vựng",
    category: "nlp",
    tags: ["embedding", "co-occurrence", "global"],
    difficulty: "intermediate",
    relatedSlugs: ["word2vec", "word-embeddings", "tf-idf"],
    vizType: "static",
  },
  {
    slug: "seq2seq",
    title: "Sequence-to-Sequence",
    titleVi: "Chuỗi sang chuỗi",
    description: "Kiến trúc mã hoá-giải mã biến đổi chuỗi đầu vào thành chuỗi đầu ra khác độ dài",
    category: "nlp",
    tags: ["encoder-decoder", "translation", "generation"],
    difficulty: "intermediate",
    relatedSlugs: ["rnn", "attention-mechanism", "transformer"],
    vizType: "interactive",
  },
  {
    slug: "attention-mechanism",
    title: "Attention Mechanism",
    titleVi: "Cơ chế chú ý",
    description: "Cơ chế cho phép mô hình tập trung vào phần quan trọng nhất của đầu vào khi sinh đầu ra",
    category: "nlp",
    tags: ["attention", "alignment", "context"],
    difficulty: "intermediate",
    relatedSlugs: ["self-attention", "transformer", "seq2seq"],
    vizType: "interactive",
  },
  {
    slug: "bert",
    title: "BERT",
    titleVi: "BERT",
    description: "Mô hình ngôn ngữ hai chiều được huấn luyện trước bằng kỹ thuật che từ và dự đoán câu kế tiếp",
    category: "nlp",
    tags: ["pre-trained", "bidirectional", "masked-lm"],
    difficulty: "intermediate",
    relatedSlugs: ["transformer", "gpt", "transfer-learning", "tokenization"],
    vizType: "static",
  },
  {
    slug: "gpt",
    title: "GPT",
    titleVi: "GPT",
    description: "Mô hình ngôn ngữ tự hồi quy sinh văn bản bằng cách dự đoán token tiếp theo",
    category: "nlp",
    tags: ["autoregressive", "generative", "language-model"],
    difficulty: "intermediate",
    relatedSlugs: ["bert", "transformer", "llm-overview", "temperature"],
    vizType: "interactive",
  },
  {
    slug: "ner",
    title: "Named Entity Recognition",
    titleVi: "Nhận dạng thực thể có tên",
    description: "Kỹ thuật trích xuất tên người, địa điểm, tổ chức từ văn bản tự nhiên",
    category: "nlp",
    tags: ["entities", "extraction", "tagging"],
    difficulty: "intermediate",
    relatedSlugs: ["tokenization", "bert", "text-classification"],
    vizType: "interactive",
  },
  {
    slug: "sentiment-analysis",
    title: "Sentiment Analysis",
    titleVi: "Phân tích cảm xúc",
    description: "Phân loại tự động thái độ, cảm xúc tích cực, tiêu cực hoặc trung tính trong văn bản",
    category: "nlp",
    tags: ["classification", "opinion", "emotion"],
    difficulty: "beginner",
    relatedSlugs: ["text-classification", "naive-bayes", "bert"],
    vizType: "interactive",
  },
  {
    slug: "perplexity-metric",
    title: "Perplexity",
    titleVi: "Độ phức tạp",
    description: "Chỉ số đo lường mức độ tự tin của mô hình ngôn ngữ khi dự đoán từ tiếp theo",
    category: "nlp",
    tags: ["evaluation", "language-model", "metric"],
    difficulty: "intermediate",
    relatedSlugs: ["gpt", "llm-overview", "temperature"],
    vizType: "interactive",
  },
  {
    slug: "beam-search",
    title: "Beam Search",
    titleVi: "Tìm kiếm chùm",
    description: "Thuật toán giải mã giữ lại nhiều ứng viên tốt nhất ở mỗi bước để tìm chuỗi tối ưu",
    category: "nlp",
    tags: ["decoding", "search", "generation"],
    difficulty: "intermediate",
    relatedSlugs: ["gpt", "top-k-top-p", "temperature"],
    vizType: "interactive",
  },
  {
    slug: "text-classification",
    title: "Text Classification",
    titleVi: "Phân loại văn bản",
    description: "Bài toán gán nhãn tự động cho văn bản vào các danh mục đã định sẵn",
    category: "nlp",
    tags: ["classification", "nlp-pipeline", "categories"],
    difficulty: "beginner",
    relatedSlugs: ["sentiment-analysis", "naive-bayes", "bert"],
    vizType: "static",
  },

  // ═══════════════════════════════════════════════════════
  // Category 5: computer-vision (14 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "image-classification",
    title: "Image Classification",
    titleVi: "Phân loại hình ảnh",
    description: "Bài toán gán nhãn cho toàn bộ hình ảnh vào một trong các lớp đã định nghĩa",
    category: "computer-vision",
    tags: ["classification", "cnn", "labels"],
    difficulty: "beginner",
    relatedSlugs: ["cnn", "transfer-learning", "feature-extraction-cnn"],
    vizType: "static",
  },
  {
    slug: "object-detection",
    title: "Object Detection (YOLO)",
    titleVi: "Phát hiện đối tượng",
    description: "Bài toán xác định vị trí và phân loại nhiều đối tượng trong cùng một hình ảnh",
    category: "computer-vision",
    tags: ["yolo", "bounding-box", "detection"],
    difficulty: "intermediate",
    relatedSlugs: ["cnn", "anchor-boxes", "nms", "iou"],
    vizType: "interactive",
  },
  {
    slug: "semantic-segmentation",
    title: "Semantic Segmentation",
    titleVi: "Phân đoạn ngữ nghĩa",
    description: "Gán nhãn cho từng pixel của ảnh thuộc về loại đối tượng nào trong cảnh",
    category: "computer-vision",
    tags: ["segmentation", "pixel-wise", "scene"],
    difficulty: "intermediate",
    relatedSlugs: ["instance-segmentation", "panoptic-segmentation", "u-net"],
    vizType: "interactive",
  },
  {
    slug: "instance-segmentation",
    title: "Instance Segmentation",
    titleVi: "Phân đoạn thực thể",
    description: "Kết hợp phát hiện đối tượng và phân đoạn để phân biệt từng thực thể riêng lẻ",
    category: "computer-vision",
    tags: ["segmentation", "instance", "mask"],
    difficulty: "advanced",
    relatedSlugs: ["semantic-segmentation", "object-detection", "panoptic-segmentation"],
    vizType: "interactive",
  },
  {
    slug: "feature-extraction-cnn",
    title: "Feature Extraction (CNN)",
    titleVi: "Trích xuất đặc trưng",
    description: "Quá trình mạng CNN tự động học và trích xuất các đặc trưng từ hình ảnh qua nhiều lớp",
    category: "computer-vision",
    tags: ["features", "activations", "layers"],
    difficulty: "intermediate",
    relatedSlugs: ["cnn", "convolution", "transfer-learning"],
    vizType: "interactive",
  },
  {
    slug: "data-augmentation",
    title: "Data Augmentation",
    titleVi: "Tăng cường dữ liệu",
    description: "Kỹ thuật tạo thêm dữ liệu huấn luyện bằng cách biến đổi ảnh gốc (xoay, lật, cắt)",
    category: "computer-vision",
    tags: ["augmentation", "training", "generalization"],
    difficulty: "beginner",
    relatedSlugs: ["overfitting-underfitting", "image-classification", "cnn"],
    vizType: "interactive",
  },
  {
    slug: "image-kernels",
    title: "Image Kernels & Filters",
    titleVi: "Bộ lọc hình ảnh",
    description: "Ma trận nhỏ trượt trên ảnh để phát hiện cạnh, làm mờ hoặc tăng nét hình ảnh",
    category: "computer-vision",
    tags: ["kernel", "edge-detection", "blur"],
    difficulty: "beginner",
    relatedSlugs: ["convolution", "cnn", "feature-extraction-cnn"],
    vizType: "interactive",
  },
  {
    slug: "anchor-boxes",
    title: "Anchor Boxes",
    titleVi: "Hộp neo",
    description: "Tập hợp hộp tham chiếu với kích thước và tỷ lệ khác nhau dùng trong phát hiện đối tượng",
    category: "computer-vision",
    tags: ["detection", "anchors", "aspect-ratio"],
    difficulty: "intermediate",
    relatedSlugs: ["object-detection", "nms", "iou"],
    vizType: "interactive",
  },
  {
    slug: "nms",
    title: "Non-Maximum Suppression",
    titleVi: "Triệt tiêu cực đại",
    description: "Thuật toán loại bỏ các hộp dự đoán trùng lặp, giữ lại hộp có độ tin cậy cao nhất",
    category: "computer-vision",
    tags: ["detection", "post-processing", "filtering"],
    difficulty: "intermediate",
    relatedSlugs: ["object-detection", "iou", "anchor-boxes"],
    vizType: "interactive",
  },
  {
    slug: "iou",
    title: "Intersection over Union",
    titleVi: "Giao trên Hợp",
    description: "Chỉ số đo mức độ trùng khớp giữa hộp dự đoán và hộp thực tế trong bài toán phát hiện",
    category: "computer-vision",
    tags: ["metric", "overlap", "evaluation"],
    difficulty: "beginner",
    relatedSlugs: ["object-detection", "nms", "anchor-boxes"],
    vizType: "interactive",
  },
  {
    slug: "color-spaces",
    title: "Color Spaces",
    titleVi: "Không gian màu",
    description: "Các hệ thống biểu diễn màu sắc (RGB, HSV, Grayscale) và ứng dụng trong xử lý ảnh",
    category: "computer-vision",
    tags: ["rgb", "hsv", "grayscale"],
    difficulty: "beginner",
    relatedSlugs: ["image-kernels", "data-augmentation", "cnn"],
    vizType: "interactive",
  },
  {
    slug: "optical-flow",
    title: "Optical Flow",
    titleVi: "Dòng quang học",
    description: "Kỹ thuật ước lượng chuyển động của các pixel giữa các khung hình liên tiếp trong video",
    category: "computer-vision",
    tags: ["motion", "video", "tracking"],
    difficulty: "advanced",
    relatedSlugs: ["cnn", "feature-extraction-cnn", "text-to-video"],
    vizType: "interactive",
  },
  {
    slug: "style-transfer",
    title: "Neural Style Transfer",
    titleVi: "Chuyển đổi phong cách",
    description: "Kỹ thuật kết hợp nội dung ảnh gốc với phong cách nghệ thuật của ảnh khác",
    category: "computer-vision",
    tags: ["style", "artistic", "cnn"],
    difficulty: "intermediate",
    relatedSlugs: ["cnn", "feature-extraction-cnn", "transfer-learning"],
    vizType: "static",
  },
  {
    slug: "panoptic-segmentation",
    title: "Panoptic Segmentation",
    titleVi: "Phân đoạn toàn cảnh",
    description: "Kết hợp phân đoạn ngữ nghĩa và thực thể để hiểu toàn diện mọi pixel trong ảnh",
    category: "computer-vision",
    tags: ["segmentation", "unified", "scene-understanding"],
    difficulty: "advanced",
    relatedSlugs: ["semantic-segmentation", "instance-segmentation", "object-detection"],
    vizType: "static",
  },

  // ═══════════════════════════════════════════════════════
  // Category 6: search-retrieval (8 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "rag",
    title: "Retrieval-Augmented Generation",
    titleVi: "Tạo sinh tăng cường truy xuất",
    description: "Kỹ thuật kết hợp tìm kiếm tài liệu với mô hình ngôn ngữ để trả lời chính xác hơn",
    category: "search-retrieval",
    tags: ["llm", "search", "retrieval"],
    difficulty: "intermediate",
    relatedSlugs: ["vector-databases", "semantic-search", "chunking", "embedding-model"],
    vizType: "interactive",
  },
  {
    slug: "vector-databases",
    title: "Vector Databases",
    titleVi: "Cơ sở dữ liệu vector",
    description: "Hệ thống lưu trữ và tìm kiếm nhanh các vector nhúng cho ứng dụng AI",
    category: "search-retrieval",
    tags: ["database", "embeddings", "similarity"],
    difficulty: "intermediate",
    relatedSlugs: ["faiss", "rag", "embedding-model", "semantic-search"],
    vizType: "interactive",
  },
  {
    slug: "faiss",
    title: "FAISS",
    titleVi: "FAISS",
    description: "Thư viện tìm kiếm tương tự vector hiệu quả cao do Meta phát triển",
    category: "search-retrieval",
    tags: ["indexing", "similarity-search", "meta"],
    difficulty: "intermediate",
    relatedSlugs: ["vector-databases", "semantic-search", "rag"],
    vizType: "interactive",
  },
  {
    slug: "bm25",
    title: "BM25 & Lexical Search",
    titleVi: "BM25 & Tìm kiếm từ khoá",
    description: "Thuật toán xếp hạng tài liệu dựa trên tần suất từ khoá và độ dài văn bản",
    category: "search-retrieval",
    tags: ["ranking", "lexical", "tf-idf"],
    difficulty: "intermediate",
    relatedSlugs: ["tf-idf", "semantic-search", "hybrid-search"],
    vizType: "static",
  },
  {
    slug: "semantic-search",
    title: "Semantic Search",
    titleVi: "Tìm kiếm ngữ nghĩa",
    description: "Tìm kiếm dựa trên ý nghĩa nội dung thay vì khớp từ khoá chính xác",
    category: "search-retrieval",
    tags: ["embeddings", "similarity", "meaning"],
    difficulty: "intermediate",
    relatedSlugs: ["bm25", "hybrid-search", "vector-databases", "embedding-model"],
    vizType: "interactive",
  },
  {
    slug: "hybrid-search",
    title: "Hybrid Search",
    titleVi: "Tìm kiếm kết hợp",
    description: "Phương pháp kết hợp tìm kiếm từ khoá và ngữ nghĩa để tận dụng ưu điểm cả hai",
    category: "search-retrieval",
    tags: ["search", "combined", "ranking"],
    difficulty: "intermediate",
    relatedSlugs: ["bm25", "semantic-search", "re-ranking"],
    vizType: "interactive",
  },
  {
    slug: "re-ranking",
    title: "Re-Ranking",
    titleVi: "Xếp hạng lại",
    description: "Giai đoạn thứ hai sắp xếp lại kết quả tìm kiếm bằng mô hình chính xác hơn",
    category: "search-retrieval",
    tags: ["ranking", "two-stage", "relevance"],
    difficulty: "intermediate",
    relatedSlugs: ["hybrid-search", "semantic-search", "rag"],
    vizType: "static",
  },
  {
    slug: "chunking",
    title: "Text Chunking",
    titleVi: "Chia đoạn văn bản",
    description: "Kỹ thuật chia tài liệu dài thành các đoạn nhỏ phù hợp cho nhúng và tìm kiếm",
    category: "search-retrieval",
    tags: ["text-processing", "splitting", "overlap"],
    difficulty: "beginner",
    relatedSlugs: ["rag", "vector-databases", "embedding-model"],
    vizType: "interactive",
  },

  // ═══════════════════════════════════════════════════════
  // Category 7: llm-concepts (10 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "prompt-engineering",
    title: "Prompt Engineering",
    titleVi: "Kỹ thuật viết prompt",
    description: "Nghệ thuật thiết kế câu lệnh hiệu quả để hướng dẫn mô hình ngôn ngữ lớn",
    category: "llm-concepts",
    tags: ["prompting", "techniques", "llm"],
    difficulty: "beginner",
    relatedSlugs: ["chain-of-thought", "in-context-learning", "fine-tuning-vs-prompting"],
    vizType: "interactive",
  },
  {
    slug: "chain-of-thought",
    title: "Chain of Thought",
    titleVi: "Suy luận theo chuỗi",
    description: "Kỹ thuật yêu cầu mô hình trình bày từng bước suy luận để cải thiện độ chính xác",
    category: "llm-concepts",
    tags: ["reasoning", "step-by-step", "prompting"],
    difficulty: "beginner",
    relatedSlugs: ["prompt-engineering", "reasoning-models", "in-context-learning"],
    vizType: "static",
  },
  {
    slug: "in-context-learning",
    title: "In-Context Learning",
    titleVi: "Học trong ngữ cảnh",
    description: "Khả năng LLM học từ các ví dụ được cung cấp trực tiếp trong prompt mà không cần huấn luyện lại",
    category: "llm-concepts",
    tags: ["few-shot", "zero-shot", "prompting"],
    difficulty: "beginner",
    relatedSlugs: ["prompt-engineering", "chain-of-thought", "fine-tuning-vs-prompting"],
    vizType: "static",
  },
  {
    slug: "hallucination",
    title: "AI Hallucination",
    titleVi: "Ảo giác AI",
    description: "Hiện tượng mô hình tự tin sinh ra thông tin sai lệch hoặc bịa đặt không có cơ sở",
    category: "llm-concepts",
    tags: ["reliability", "factuality", "safety"],
    difficulty: "beginner",
    relatedSlugs: ["rag", "guardrails", "temperature"],
    vizType: "interactive",
  },
  {
    slug: "temperature",
    title: "Temperature",
    titleVi: "Nhiệt độ",
    description: "Tham số điều chỉnh mức độ ngẫu nhiên trong phân phối xác suất khi sinh văn bản",
    category: "llm-concepts",
    tags: ["sampling", "randomness", "generation"],
    difficulty: "beginner",
    relatedSlugs: ["top-k-top-p", "beam-search", "gpt"],
    vizType: "interactive",
  },
  {
    slug: "top-k-top-p",
    title: "Top-K & Top-P Sampling",
    titleVi: "Lấy mẫu Top-K & Top-P",
    description: "Các phương pháp lọc lựa chọn token khi sinh văn bản để cân bằng chất lượng và đa dạng",
    category: "llm-concepts",
    tags: ["sampling", "nucleus", "generation"],
    difficulty: "intermediate",
    relatedSlugs: ["temperature", "beam-search", "gpt"],
    vizType: "interactive",
  },
  {
    slug: "context-window",
    title: "Context Window",
    titleVi: "Cửa sổ ngữ cảnh",
    description: "Giới hạn số lượng token mà mô hình có thể xử lý trong một lần suy luận",
    category: "llm-concepts",
    tags: ["tokens", "memory", "limitation"],
    difficulty: "beginner",
    relatedSlugs: ["tokenization", "long-context", "self-attention"],
    vizType: "interactive",
  },
  {
    slug: "llm-overview",
    title: "Large Language Models",
    titleVi: "Mô hình ngôn ngữ lớn",
    description: "Tổng quan về các mô hình ngôn ngữ quy mô lớn, kiến trúc và khả năng của chúng",
    category: "llm-concepts",
    tags: ["language-model", "scale", "capabilities"],
    difficulty: "beginner",
    relatedSlugs: ["gpt", "transformer", "fine-tuning-vs-prompting"],
    vizType: "static",
  },
  {
    slug: "fine-tuning-vs-prompting",
    title: "Fine-tuning vs Prompting",
    titleVi: "Tinh chỉnh vs Viết prompt",
    description: "So sánh hai cách tiếp cận chính để tuỳ chỉnh hành vi của mô hình ngôn ngữ lớn",
    category: "llm-concepts",
    tags: ["comparison", "adaptation", "llm"],
    difficulty: "intermediate",
    relatedSlugs: ["fine-tuning", "prompt-engineering", "in-context-learning"],
    vizType: "static",
  },
  {
    slug: "embedding-model",
    title: "Embedding Models",
    titleVi: "Mô hình nhúng",
    description: "Mô hình chuyển đổi văn bản thành vector số học để đo lường độ tương đồng ngữ nghĩa",
    category: "llm-concepts",
    tags: ["embeddings", "vectors", "similarity"],
    difficulty: "intermediate",
    relatedSlugs: ["word-embeddings", "vector-databases", "semantic-search", "rag"],
    vizType: "interactive",
  },

  // ═══════════════════════════════════════════════════════
  // Category 8: training-optimization (10 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "fine-tuning",
    title: "Fine-Tuning",
    titleVi: "Tinh chỉnh mô hình",
    description: "Quá trình huấn luyện thêm mô hình đã pre-train trên dữ liệu chuyên biệt cho tác vụ cụ thể",
    category: "training-optimization",
    tags: ["adaptation", "pre-trained", "domain"],
    difficulty: "intermediate",
    relatedSlugs: ["lora", "qlora", "transfer-learning", "fine-tuning-vs-prompting"],
    vizType: "static",
  },
  {
    slug: "lora",
    title: "LoRA",
    titleVi: "LoRA",
    description: "Kỹ thuật tinh chỉnh hiệu quả bằng cách thêm ma trận hạng thấp, giữ nguyên trọng số gốc",
    category: "training-optimization",
    tags: ["efficient", "low-rank", "adaptation"],
    difficulty: "advanced",
    relatedSlugs: ["fine-tuning", "qlora", "quantization"],
    vizType: "interactive",
  },
  {
    slug: "qlora",
    title: "QLoRA",
    titleVi: "QLoRA",
    description: "Kết hợp lượng tử hoá và LoRA để tinh chỉnh mô hình lớn trên GPU bộ nhớ hạn chế",
    category: "training-optimization",
    tags: ["quantized", "efficient", "memory"],
    difficulty: "advanced",
    relatedSlugs: ["lora", "quantization", "fine-tuning"],
    vizType: "static",
  },
  {
    slug: "rlhf",
    title: "RLHF",
    titleVi: "Học tăng cường từ phản hồi con người",
    description: "Phương pháp căn chỉnh mô hình theo sở thích con người thông qua học tăng cường",
    category: "training-optimization",
    tags: ["alignment", "reward-model", "human-feedback"],
    difficulty: "advanced",
    relatedSlugs: ["dpo", "grpo", "alignment", "fine-tuning"],
    vizType: "interactive",
  },
  {
    slug: "dpo",
    title: "Direct Preference Optimization",
    titleVi: "Tối ưu sở thích trực tiếp",
    description: "Phương pháp căn chỉnh mô hình đơn giản hơn RLHF, loại bỏ nhu cầu mô hình thưởng riêng",
    category: "training-optimization",
    tags: ["alignment", "preference", "simplified"],
    difficulty: "advanced",
    relatedSlugs: ["rlhf", "grpo", "fine-tuning"],
    vizType: "static",
  },
  {
    slug: "quantization",
    title: "Quantization",
    titleVi: "Lượng tử hoá",
    description: "Kỹ thuật giảm độ chính xác số của trọng số mô hình để giảm kích thước và tăng tốc suy luận",
    category: "training-optimization",
    tags: ["compression", "precision", "efficiency"],
    difficulty: "intermediate",
    relatedSlugs: ["qlora", "pruning", "inference-optimization"],
    vizType: "interactive",
  },
  {
    slug: "distillation",
    title: "Knowledge Distillation",
    titleVi: "Chưng cất kiến thức",
    description: "Kỹ thuật truyền kiến thức từ mô hình lớn (teacher) sang mô hình nhỏ hơn (student)",
    category: "training-optimization",
    tags: ["teacher-student", "compression", "transfer"],
    difficulty: "intermediate",
    relatedSlugs: ["pruning", "quantization", "small-language-models"],
    vizType: "interactive",
  },
  {
    slug: "pruning",
    title: "Model Pruning",
    titleVi: "Cắt tỉa mô hình",
    description: "Kỹ thuật loại bỏ các kết nối và nơ-ron không quan trọng để giảm kích thước mô hình",
    category: "training-optimization",
    tags: ["compression", "sparsity", "efficiency"],
    difficulty: "intermediate",
    relatedSlugs: ["quantization", "distillation", "inference-optimization"],
    vizType: "interactive",
  },
  {
    slug: "mixed-precision",
    title: "Mixed Precision Training",
    titleVi: "Huấn luyện hỗn hợp độ chính xác",
    description: "Kỹ thuật dùng đồng thời FP16 và FP32 để huấn luyện nhanh hơn và tiết kiệm bộ nhớ",
    category: "training-optimization",
    tags: ["fp16", "fp32", "efficiency"],
    difficulty: "intermediate",
    relatedSlugs: ["quantization", "gpu-optimization", "fine-tuning"],
    vizType: "static",
  },
  {
    slug: "grpo",
    title: "GRPO",
    titleVi: "GRPO",
    description: "Phương pháp tối ưu sở thích nhóm, cải tiến từ PPO và DPO cho việc căn chỉnh mô hình",
    category: "training-optimization",
    tags: ["alignment", "group", "optimization"],
    difficulty: "advanced",
    relatedSlugs: ["rlhf", "dpo", "fine-tuning"],
    vizType: "static",
  },

  // ═══════════════════════════════════════════════════════
  // Category 9: ai-agents (9 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "function-calling",
    title: "Function Calling",
    titleVi: "Gọi hàm",
    description: "Khả năng LLM tạo lệnh gọi hàm có cấu trúc JSON để tương tác với công cụ bên ngoài",
    category: "ai-agents",
    tags: ["tools", "json", "api"],
    difficulty: "intermediate",
    relatedSlugs: ["react-framework", "agent-architecture", "orchestration"],
    vizType: "interactive",
  },
  {
    slug: "react-framework",
    title: "ReAct Framework",
    titleVi: "Khung ReAct",
    description: "Mô hình kết hợp Suy nghĩ, Hành động và Quan sát để giải quyết tác vụ phức tạp",
    category: "ai-agents",
    tags: ["reasoning", "action", "observation"],
    difficulty: "intermediate",
    relatedSlugs: ["function-calling", "agent-architecture", "planning"],
    vizType: "interactive",
  },
  {
    slug: "agent-architecture",
    title: "Agent Architecture",
    titleVi: "Kiến trúc Agent",
    description: "Thiết kế tổng thể các thành phần cấu thành một AI Agent tự chủ",
    category: "ai-agents",
    tags: ["design", "components", "autonomy"],
    difficulty: "intermediate",
    relatedSlugs: ["react-framework", "planning", "memory-systems", "agentic-workflows"],
    vizType: "interactive",
  },
  {
    slug: "planning",
    title: "Planning",
    titleVi: "Lập kế hoạch",
    description: "Khả năng Agent phân rã mục tiêu phức tạp thành chuỗi các bước hành động nhỏ hơn",
    category: "ai-agents",
    tags: ["decomposition", "task-planning", "strategy"],
    difficulty: "intermediate",
    relatedSlugs: ["react-framework", "agent-architecture", "chain-of-thought"],
    vizType: "interactive",
  },
  {
    slug: "memory-systems",
    title: "Memory Systems",
    titleVi: "Hệ thống bộ nhớ",
    description: "Cơ chế lưu trữ và truy xuất thông tin ngắn hạn và dài hạn cho AI Agent",
    category: "ai-agents",
    tags: ["short-term", "long-term", "retrieval"],
    difficulty: "intermediate",
    relatedSlugs: ["agent-architecture", "context-window", "vector-databases"],
    vizType: "interactive",
  },
  {
    slug: "multi-agent",
    title: "Multi-Agent Systems",
    titleVi: "Hệ thống đa tác tử",
    description: "Nhiều AI Agent phối hợp với nhau, mỗi agent có vai trò chuyên biệt",
    category: "ai-agents",
    tags: ["collaboration", "multi-agent", "coordination"],
    difficulty: "advanced",
    relatedSlugs: ["agent-architecture", "agentic-workflows", "orchestration"],
    vizType: "interactive",
  },
  {
    slug: "agentic-workflows",
    title: "Agentic Workflows",
    titleVi: "Quy trình Agent",
    description: "Các mẫu thiết kế quy trình làm việc cho AI Agent với phân nhánh và lặp",
    category: "ai-agents",
    tags: ["workflow", "patterns", "automation"],
    difficulty: "intermediate",
    relatedSlugs: ["agent-architecture", "multi-agent", "orchestration"],
    vizType: "interactive",
  },
  {
    slug: "agent-evaluation",
    title: "Agent Evaluation",
    titleVi: "Đánh giá Agent",
    description: "Phương pháp đo lường và so sánh hiệu suất của các AI Agent trên các tác vụ thực tế",
    category: "ai-agents",
    tags: ["benchmarks", "metrics", "testing"],
    difficulty: "intermediate",
    relatedSlugs: ["agent-architecture", "agentic-workflows", "guardrails"],
    vizType: "static",
  },
  {
    slug: "orchestration",
    title: "Orchestration (LangChain, LlamaIndex)",
    titleVi: "Điều phối",
    description: "Các framework giúp kết nối LLM với công cụ, dữ liệu và quy trình làm việc",
    category: "ai-agents",
    tags: ["langchain", "llamaindex", "framework"],
    difficulty: "intermediate",
    relatedSlugs: ["function-calling", "rag", "agent-architecture"],
    vizType: "static",
  },

  // ═══════════════════════════════════════════════════════
  // Category 10: multimodal (8 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "vlm",
    title: "Vision-Language Models",
    titleVi: "Mô hình Ngôn ngữ-Thị giác",
    description: "Mô hình kết hợp hiểu hình ảnh và ngôn ngữ để trả lời câu hỏi về ảnh",
    category: "multimodal",
    tags: ["vision", "language", "multimodal"],
    difficulty: "intermediate",
    relatedSlugs: ["clip", "unified-multimodal", "image-classification"],
    vizType: "interactive",
  },
  {
    slug: "text-to-image",
    title: "Text-to-Image Generation",
    titleVi: "Sinh ảnh từ văn bản",
    description: "Mô hình tạo hình ảnh từ mô tả văn bản tự nhiên (Stable Diffusion, DALL-E)",
    category: "multimodal",
    tags: ["generation", "diffusion", "creative"],
    difficulty: "intermediate",
    relatedSlugs: ["diffusion-models", "clip", "gan"],
    vizType: "interactive",
  },
  {
    slug: "text-to-video",
    title: "Text-to-Video Generation",
    titleVi: "Sinh video từ văn bản",
    description: "Mô hình tạo video từ mô tả văn bản, mở rộng từ sinh ảnh sang chuỗi khung hình",
    category: "multimodal",
    tags: ["video", "generation", "temporal"],
    difficulty: "advanced",
    relatedSlugs: ["text-to-image", "diffusion-models", "optical-flow"],
    vizType: "static",
  },
  {
    slug: "speech-recognition",
    title: "Speech Recognition",
    titleVi: "Nhận dạng giọng nói",
    description: "Công nghệ chuyển đổi giọng nói thành văn bản tự động (ASR/STT)",
    category: "multimodal",
    tags: ["audio", "transcription", "whisper"],
    difficulty: "intermediate",
    relatedSlugs: ["tts", "tokenization", "seq2seq"],
    vizType: "interactive",
  },
  {
    slug: "tts",
    title: "Text-to-Speech",
    titleVi: "Chuyển văn bản thành giọng nói",
    description: "Công nghệ tổng hợp giọng nói tự nhiên từ văn bản đầu vào",
    category: "multimodal",
    tags: ["audio", "synthesis", "voice"],
    difficulty: "intermediate",
    relatedSlugs: ["speech-recognition", "seq2seq", "transformer"],
    vizType: "interactive",
  },
  {
    slug: "clip",
    title: "CLIP & Contrastive Learning",
    titleVi: "CLIP & Học tương phản",
    description: "Mô hình học liên kết ảnh-văn bản bằng học tương phản trên dữ liệu web quy mô lớn",
    category: "multimodal",
    tags: ["contrastive", "image-text", "openai"],
    difficulty: "advanced",
    relatedSlugs: ["vlm", "text-to-image", "word-embeddings"],
    vizType: "interactive",
  },
  {
    slug: "unified-multimodal",
    title: "Unified Multimodal Architecture",
    titleVi: "Kiến trúc đa phương thức thống nhất",
    description: "Kiến trúc dùng chung một backbone cho nhiều loại dữ liệu (ảnh, văn bản, âm thanh)",
    category: "multimodal",
    tags: ["unified", "backbone", "architecture"],
    difficulty: "advanced",
    relatedSlugs: ["vlm", "clip", "transformer"],
    vizType: "static",
  },
  {
    slug: "tlm",
    title: "Trustworthy Language Models",
    titleVi: "Mô hình ngôn ngữ đáng tin cậy",
    description: "Mô hình ngôn ngữ với khả năng đánh giá độ tin cậy và mức độ chắc chắn của câu trả lời",
    category: "ai-safety",
    tags: ["trustworthy", "confidence", "reliability"],
    difficulty: "intermediate",
    relatedSlugs: ["hallucination", "guardrails", "llm-overview"],
    vizType: "interactive",
  },

  // ═══════════════════════════════════════════════════════
  // Category 11: ai-safety (8 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "alignment",
    title: "AI Alignment",
    titleVi: "Căn chỉnh AI",
    description: "Bài toán đảm bảo hành vi AI phù hợp với ý định và giá trị của con người",
    category: "ai-safety",
    tags: ["safety", "values", "goals"],
    difficulty: "intermediate",
    relatedSlugs: ["rlhf", "constitutional-ai", "guardrails"],
    vizType: "static",
  },
  {
    slug: "red-teaming",
    title: "Red Teaming",
    titleVi: "Kiểm thử đối kháng",
    description: "Phương pháp kiểm tra lỗ hổng AI bằng cách cố tình tấn công với prompt đối kháng",
    category: "ai-safety",
    tags: ["adversarial", "testing", "vulnerability"],
    difficulty: "intermediate",
    relatedSlugs: ["guardrails", "adversarial-robustness", "alignment"],
    vizType: "interactive",
  },
  {
    slug: "bias-fairness",
    title: "Bias & Fairness",
    titleVi: "Thiên kiến & Công bằng",
    description: "Phát hiện và giảm thiểu thiên kiến trong dữ liệu và mô hình AI để đảm bảo công bằng",
    category: "ai-safety",
    tags: ["bias", "fairness", "demographics"],
    difficulty: "intermediate",
    relatedSlugs: ["explainability", "ai-governance", "alignment"],
    vizType: "interactive",
  },
  {
    slug: "explainability",
    title: "Explainability (XAI)",
    titleVi: "Giải thích được",
    description: "Các kỹ thuật giúp hiểu và giải thích tại sao mô hình AI đưa ra quyết định cụ thể",
    category: "ai-safety",
    tags: ["interpretability", "shap", "attention"],
    difficulty: "intermediate",
    relatedSlugs: ["bias-fairness", "guardrails", "self-attention"],
    vizType: "interactive",
  },
  {
    slug: "guardrails",
    title: "AI Guardrails",
    titleVi: "Rào chắn an toàn",
    description: "Hệ thống lọc và kiểm soát đầu vào/đầu ra của mô hình AI để ngăn nội dung có hại",
    category: "ai-safety",
    tags: ["safety", "filtering", "moderation"],
    difficulty: "intermediate",
    relatedSlugs: ["alignment", "red-teaming", "hallucination"],
    vizType: "interactive",
  },
  {
    slug: "constitutional-ai",
    title: "Constitutional AI",
    titleVi: "AI Hiến pháp",
    description: "Phương pháp huấn luyện AI tự phê bình và sửa đổi dựa trên bộ nguyên tắc đã định",
    category: "ai-safety",
    tags: ["critique", "revision", "principles"],
    difficulty: "advanced",
    relatedSlugs: ["alignment", "rlhf", "guardrails"],
    vizType: "static",
  },
  {
    slug: "ai-governance",
    title: "AI Governance",
    titleVi: "Quản trị AI",
    description: "Khung pháp lý, chính sách và quy định về phát triển và triển khai AI có trách nhiệm",
    category: "ai-safety",
    tags: ["regulation", "policy", "ethics"],
    difficulty: "beginner",
    relatedSlugs: ["bias-fairness", "alignment", "explainability"],
    vizType: "static",
  },
  {
    slug: "adversarial-robustness",
    title: "Adversarial Robustness",
    titleVi: "Khả năng chống đối kháng",
    description: "Khả năng mô hình AI duy trì hiệu suất trước các nhiễu loạn và tấn công có chủ đích",
    category: "ai-safety",
    tags: ["robustness", "perturbation", "defense"],
    difficulty: "advanced",
    relatedSlugs: ["red-teaming", "guardrails", "data-augmentation"],
    vizType: "interactive",
  },

  // ═══════════════════════════════════════════════════════
  // Category 12: infrastructure (8 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "model-serving",
    title: "Model Serving",
    titleVi: "Phục vụ mô hình",
    description: "Hạ tầng và kỹ thuật triển khai mô hình AI để phục vụ yêu cầu suy luận trong sản xuất",
    category: "infrastructure",
    tags: ["deployment", "api", "serving"],
    difficulty: "intermediate",
    relatedSlugs: ["inference-optimization", "containerization", "mlops"],
    vizType: "static",
  },
  {
    slug: "inference-optimization",
    title: "Inference Optimization",
    titleVi: "Tối ưu suy luận",
    description: "Các kỹ thuật giảm độ trễ và tăng thông lượng khi chạy mô hình AI trong sản xuất",
    category: "infrastructure",
    tags: ["latency", "throughput", "optimization"],
    difficulty: "intermediate",
    relatedSlugs: ["quantization", "pruning", "model-serving"],
    vizType: "interactive",
  },
  {
    slug: "edge-ai",
    title: "Edge AI",
    titleVi: "AI biên",
    description: "Triển khai mô hình AI trực tiếp trên thiết bị đầu cuối thay vì trên đám mây",
    category: "infrastructure",
    tags: ["edge", "mobile", "on-device"],
    difficulty: "intermediate",
    relatedSlugs: ["quantization", "small-language-models", "inference-optimization"],
    vizType: "static",
  },
  {
    slug: "mlops",
    title: "MLOps",
    titleVi: "MLOps",
    description: "Quy trình tự động hoá vòng đời phát triển, triển khai và giám sát mô hình ML",
    category: "infrastructure",
    tags: ["devops", "pipeline", "automation"],
    difficulty: "intermediate",
    relatedSlugs: ["model-serving", "monitoring", "containerization"],
    vizType: "interactive",
  },
  {
    slug: "monitoring",
    title: "Model Monitoring",
    titleVi: "Giám sát mô hình",
    description: "Theo dõi hiệu suất mô hình trong sản xuất để phát hiện suy giảm và lỗi kịp thời",
    category: "infrastructure",
    tags: ["drift", "performance", "alerts"],
    difficulty: "intermediate",
    relatedSlugs: ["mlops", "model-serving", "bias-fairness"],
    vizType: "interactive",
  },
  {
    slug: "containerization",
    title: "Containerization",
    titleVi: "Container hoá",
    description: "Đóng gói mô hình và dependencies vào container Docker để triển khai nhất quán",
    category: "infrastructure",
    tags: ["docker", "kubernetes", "deployment"],
    difficulty: "intermediate",
    relatedSlugs: ["model-serving", "mlops", "gpu-optimization"],
    vizType: "static",
  },
  {
    slug: "gpu-optimization",
    title: "GPU Optimization",
    titleVi: "Tối ưu GPU",
    description: "Các chiến lược tận dụng tối đa khả năng xử lý song song của GPU cho huấn luyện AI",
    category: "infrastructure",
    tags: ["gpu", "parallelism", "cuda"],
    difficulty: "advanced",
    relatedSlugs: ["mixed-precision", "inference-optimization", "cost-optimization"],
    vizType: "static",
  },
  {
    slug: "cost-optimization",
    title: "Cost Optimization",
    titleVi: "Tối ưu chi phí",
    description: "Chiến lược giảm chi phí huấn luyện và suy luận mô hình AI mà không hy sinh hiệu suất",
    category: "infrastructure",
    tags: ["cost", "efficiency", "budget"],
    difficulty: "intermediate",
    relatedSlugs: ["quantization", "gpu-optimization", "edge-ai"],
    vizType: "static",
  },

  // ═══════════════════════════════════════════════════════
  // Category 13: emerging (9 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "reasoning-models",
    title: "Reasoning Models",
    titleVi: "Mô hình suy luận",
    description: "Mô hình AI có khả năng suy luận logic nhiều bước và giải quyết bài toán phức tạp",
    category: "emerging",
    tags: ["reasoning", "o1", "thinking"],
    difficulty: "intermediate",
    relatedSlugs: ["chain-of-thought", "test-time-compute", "llm-overview"],
    vizType: "interactive",
  },
  {
    slug: "test-time-compute",
    title: "Test-Time Compute",
    titleVi: "Tính toán lúc suy luận",
    description: "Kỹ thuật dùng thêm tài nguyên tính toán khi suy luận để cải thiện chất lượng câu trả lời",
    category: "emerging",
    tags: ["compute", "scaling", "inference"],
    difficulty: "advanced",
    relatedSlugs: ["reasoning-models", "chain-of-thought", "inference-optimization"],
    vizType: "interactive",
  },
  {
    slug: "moe",
    title: "Mixture of Experts",
    titleVi: "Hỗn hợp chuyên gia",
    description: "Kiến trúc chỉ kích hoạt một phần nhỏ tham số cho mỗi token, tăng hiệu quả mô hình lớn",
    category: "emerging",
    tags: ["routing", "sparse", "efficiency"],
    difficulty: "advanced",
    relatedSlugs: ["transformer", "llm-overview", "inference-optimization"],
    vizType: "interactive",
  },
  {
    slug: "state-space-models",
    title: "State Space Models (Mamba)",
    titleVi: "Mô hình không gian trạng thái",
    description: "Kiến trúc thay thế Transformer xử lý chuỗi dài hiệu quả với độ phức tạp O(n) thay vì O(n2)",
    category: "emerging",
    tags: ["mamba", "linear", "sequence"],
    difficulty: "advanced",
    relatedSlugs: ["transformer", "rnn", "long-context"],
    vizType: "interactive",
  },
  {
    slug: "small-language-models",
    title: "Small Language Models",
    titleVi: "Mô hình ngôn ngữ nhỏ",
    description: "Mô hình ngôn ngữ gọn nhẹ có hiệu suất cao, phù hợp triển khai trên thiết bị đầu cuối",
    category: "emerging",
    tags: ["small", "efficient", "on-device"],
    difficulty: "intermediate",
    relatedSlugs: ["distillation", "quantization", "edge-ai"],
    vizType: "static",
  },
  {
    slug: "synthetic-data",
    title: "Synthetic Data",
    titleVi: "Dữ liệu tổng hợp",
    description: "Dữ liệu được tạo nhân tạo bởi mô hình AI để bổ sung hoặc thay thế dữ liệu thực",
    category: "emerging",
    tags: ["data-generation", "augmentation", "privacy"],
    difficulty: "intermediate",
    relatedSlugs: ["data-augmentation", "gan", "fine-tuning"],
    vizType: "static",
  },
  {
    slug: "world-models",
    title: "World Models",
    titleVi: "Mô hình thế giới",
    description: "Mô hình AI xây dựng biểu diễn nội tại của thế giới để dự đoán trạng thái tiếp theo",
    category: "emerging",
    tags: ["simulation", "prediction", "environment"],
    difficulty: "advanced",
    relatedSlugs: ["reasoning-models", "supervised-unsupervised-rl", "planning"],
    vizType: "interactive",
  },
  {
    slug: "long-context",
    title: "Long Context",
    titleVi: "Ngữ cảnh dài",
    description: "Kỹ thuật mở rộng cửa sổ ngữ cảnh lên hàng triệu token cho xử lý tài liệu lớn",
    category: "emerging",
    tags: ["context-length", "attention", "scaling"],
    difficulty: "intermediate",
    relatedSlugs: ["context-window", "self-attention", "state-space-models"],
    vizType: "interactive",
  },
  {
    slug: "ai-for-science",
    title: "AI for Science",
    titleVi: "AI cho Khoa học",
    description: "Ứng dụng AI trong nghiên cứu khoa học: khám phá thuốc, dự báo thời tiết, vật liệu mới",
    category: "emerging",
    tags: ["science", "discovery", "research"],
    difficulty: "intermediate",
    relatedSlugs: ["reasoning-models", "world-models", "llm-overview"],
    vizType: "static",
  },

  // ═══════════════════════════════════════════════════════
  // Category 14: foundations (9 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "supervised-unsupervised-rl",
    title: "Supervised / Unsupervised / Reinforcement Learning",
    titleVi: "Học có giám sát / Không giám sát / Tăng cường",
    description: "Ba phương pháp học máy chính dựa trên cách dữ liệu được gán nhãn và phản hồi",
    category: "foundations",
    tags: ["paradigms", "supervised", "unsupervised", "reinforcement"],
    difficulty: "beginner",
    relatedSlugs: ["linear-regression", "k-means", "rlhf"],
    vizType: "static",
  },
  {
    slug: "feature-engineering",
    title: "Feature Engineering",
    titleVi: "Kỹ thuật đặc trưng",
    description: "Quá trình chọn lọc, tạo và biến đổi đặc trưng đầu vào để cải thiện hiệu suất mô hình",
    category: "foundations",
    tags: ["features", "selection", "transformation"],
    difficulty: "beginner",
    relatedSlugs: ["data-preprocessing", "pca", "decision-trees"],
    vizType: "interactive",
  },
  {
    slug: "train-val-test",
    title: "Train / Validation / Test Split",
    titleVi: "Chia tập dữ liệu",
    description: "Phương pháp chia dữ liệu thành ba tập để huấn luyện, tinh chỉnh và đánh giá mô hình",
    category: "foundations",
    tags: ["data-split", "evaluation", "methodology"],
    difficulty: "beginner",
    relatedSlugs: ["cross-validation", "overfitting-underfitting", "bias-variance"],
    vizType: "interactive",
  },
  {
    slug: "roc-auc",
    title: "ROC & AUC",
    titleVi: "ROC & AUC",
    description: "Đường cong ROC và diện tích AUC đánh giá khả năng phân biệt của mô hình phân loại",
    category: "foundations",
    tags: ["evaluation", "classification", "threshold"],
    difficulty: "intermediate",
    relatedSlugs: ["confusion-matrix", "logistic-regression", "cross-validation"],
    vizType: "interactive",
  },
  {
    slug: "ensemble-methods",
    title: "Ensemble Methods",
    titleVi: "Phương pháp kết hợp",
    description: "Kỹ thuật kết hợp nhiều mô hình để tạo dự đoán chính xác và ổn định hơn",
    category: "foundations",
    tags: ["bagging", "boosting", "stacking"],
    difficulty: "intermediate",
    relatedSlugs: ["random-forests", "gradient-boosting", "decision-trees"],
    vizType: "static",
  },
  {
    slug: "dimensionality-curse",
    title: "Curse of Dimensionality",
    titleVi: "Lời nguyền chiều",
    description: "Hiện tượng dữ liệu trở nên thưa thớt và khó xử lý khi số chiều đặc trưng tăng cao",
    category: "foundations",
    tags: ["dimensions", "sparsity", "high-dimensional"],
    difficulty: "intermediate",
    relatedSlugs: ["pca", "t-sne", "feature-engineering"],
    vizType: "interactive",
  },
  {
    slug: "hyperparameter-tuning",
    title: "Hyperparameter Tuning",
    titleVi: "Tinh chỉnh siêu tham số",
    description: "Quá trình tìm kiếm bộ siêu tham số tối ưu cho mô hình bằng grid search hoặc random search",
    category: "foundations",
    tags: ["grid-search", "random-search", "bayesian"],
    difficulty: "intermediate",
    relatedSlugs: ["learning-rate", "cross-validation", "overfitting-underfitting"],
    vizType: "interactive",
  },
  {
    slug: "data-preprocessing",
    title: "Data Preprocessing",
    titleVi: "Tiền xử lý dữ liệu",
    description: "Các bước làm sạch, chuẩn hoá và biến đổi dữ liệu thô trước khi đưa vào mô hình",
    category: "foundations",
    tags: ["cleaning", "normalization", "encoding"],
    difficulty: "beginner",
    relatedSlugs: ["feature-engineering", "train-val-test", "data-augmentation"],
    vizType: "static",
  },
  {
    slug: "neural-network-overview",
    title: "Neural Network Overview",
    titleVi: "Tổng quan mạng nơ-ron",
    description: "Cái nhìn toàn diện về cấu trúc, nguyên lý hoạt động và ứng dụng của mạng nơ-ron",
    category: "foundations",
    tags: ["overview", "neural-network", "introduction"],
    difficulty: "beginner",
    relatedSlugs: ["perceptron", "mlp", "backpropagation", "activation-functions"],
    vizType: "interactive",
  },
  {
    slug: "what-is-ml",
    title: "What is Machine Learning?",
    titleVi: "Machine Learning là gì?",
    description: "Giới thiệu Machine Learning — khác gì lập trình truyền thống, giải quyết bài toán nào, và tại sao quan trọng.",
    category: "foundations",
    tags: ["introduction", "machine-learning", "basics"],
    difficulty: "beginner",
    relatedSlugs: ["supervised-unsupervised-rl", "linear-regression", "data-preprocessing"],
    vizType: "interactive",
  },
  {
    slug: "python-for-ml",
    title: "Python for Machine Learning",
    titleVi: "Python cho Machine Learning",
    description: "Cơ bản NumPy, Pandas, và Matplotlib — ba công cụ không thể thiếu khi làm ML.",
    category: "foundations",
    tags: ["python", "numpy", "pandas", "matplotlib", "tools"],
    difficulty: "beginner",
    relatedSlugs: ["data-preprocessing", "feature-engineering", "jupyter-colab-workflow"],
    vizType: "interactive",
  },
  {
    slug: "model-evaluation-selection",
    title: "Model Evaluation & Selection",
    titleVi: "Đánh giá và Chọn mô hình",
    description: "Cách chọn thuật toán phù hợp cho bài toán cụ thể — flowchart quyết định, so sánh metrics.",
    category: "classic-ml",
    tags: ["evaluation", "model-selection", "metrics", "comparison"],
    difficulty: "beginner",
    relatedSlugs: ["confusion-matrix", "bias-variance", "cross-validation", "overfitting-underfitting"],
    vizType: "interactive",
  },
  {
    slug: "jupyter-colab-workflow",
    title: "Jupyter & Google Colab Workflow",
    titleVi: "Quy trình làm việc với Jupyter và Google Colab",
    description: "Hướng dẫn thực hành — cách chạy thí nghiệm ML đầu tiên trên Jupyter Notebook và Google Colab.",
    category: "foundations",
    tags: ["jupyter", "colab", "notebook", "tools", "workflow"],
    difficulty: "beginner",
    relatedSlugs: ["python-for-ml", "data-preprocessing", "end-to-end-ml-project"],
    vizType: "interactive",
  },
  {
    slug: "end-to-end-ml-project",
    title: "End-to-End ML Project",
    titleVi: "Dự án ML từ A đến Z",
    description: "Capstone — hoàn thành dự án ML hoàn chỉnh: thu thập dữ liệu → tiền xử lý → huấn luyện → đánh giá → diễn giải kết quả.",
    category: "foundations",
    tags: ["project", "pipeline", "end-to-end", "capstone"],
    difficulty: "beginner",
    relatedSlugs: ["data-preprocessing", "feature-engineering", "model-evaluation-selection", "python-for-ml"],
    vizType: "interactive",
  },

  // ═══════════════════════════════════════════════════════
  // Category 15: reinforcement-learning (5 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "q-learning",
    title: "Q-Learning",
    titleVi: "Q-Learning",
    description: "Thuật toán học tăng cường cơ bản học giá trị hành động tối ưu từ trải nghiệm",
    category: "reinforcement-learning",
    tags: ["reinforcement", "q-table", "reward"],
    difficulty: "beginner",
    relatedSlugs: ["deep-q-network", "multi-armed-bandit", "supervised-unsupervised-rl"],
    vizType: "interactive",
  },
  {
    slug: "deep-q-network",
    title: "Deep Q-Network (DQN)",
    titleVi: "Mạng Q sâu",
    description: "Kết hợp Q-Learning với mạng nơ-ron sâu để xử lý không gian trạng thái lớn",
    category: "reinforcement-learning",
    tags: ["deep-rl", "atari", "experience-replay"],
    difficulty: "intermediate",
    relatedSlugs: ["q-learning", "actor-critic", "mlp"],
    vizType: "interactive",
  },
  {
    slug: "policy-gradient",
    title: "Policy Gradient",
    titleVi: "Gradient chính sách",
    description: "Phương pháp tối ưu trực tiếp chính sách hành động bằng gradient ascent trên phần thưởng kỳ vọng",
    category: "reinforcement-learning",
    tags: ["reinforce", "policy", "optimization"],
    difficulty: "intermediate",
    relatedSlugs: ["actor-critic", "q-learning", "gradient-descent"],
    vizType: "interactive",
  },
  {
    slug: "actor-critic",
    title: "Actor-Critic (A2C/A3C)",
    titleVi: "Actor-Critic",
    description: "Kiến trúc kết hợp mạng chính sách (Actor) và mạng đánh giá (Critic) để học ổn định hơn",
    category: "reinforcement-learning",
    tags: ["a2c", "a3c", "advantage"],
    difficulty: "advanced",
    relatedSlugs: ["policy-gradient", "deep-q-network", "rlhf"],
    vizType: "interactive",
  },
  {
    slug: "multi-armed-bandit",
    title: "Multi-Armed Bandit",
    titleVi: "Bài toán máy đánh bạc nhiều tay",
    description: "Bài toán cân bằng giữa khai thác kiến thức đã có và khám phá lựa chọn mới",
    category: "reinforcement-learning",
    tags: ["exploration", "exploitation", "epsilon-greedy"],
    difficulty: "beginner",
    relatedSlugs: ["q-learning", "recommendation-systems", "supervised-unsupervised-rl"],
    vizType: "interactive",
  },

  // ═══════════════════════════════════════════════════════
  // Category 16: applied-ai (5 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "recommendation-systems",
    title: "Recommendation Systems",
    titleVi: "Hệ thống gợi ý",
    description: "Hệ thống gợi ý sản phẩm, nội dung dựa trên lọc cộng tác, lọc nội dung và phương pháp lai",
    category: "applied-ai",
    tags: ["collaborative-filtering", "content-based", "personalization"],
    difficulty: "intermediate",
    relatedSlugs: ["embedding-model", "multi-armed-bandit", "k-means"],
    vizType: "interactive",
  },
  {
    slug: "ai-in-healthcare",
    title: "AI in Healthcare",
    titleVi: "AI trong Y tế",
    description: "Ứng dụng AI trong chẩn đoán hình ảnh y khoa, phát triển thuốc và dự đoán bệnh",
    category: "applied-ai",
    tags: ["medical", "diagnosis", "drug-discovery"],
    difficulty: "beginner",
    relatedSlugs: ["image-classification", "cnn", "ai-for-science"],
    vizType: "static",
  },
  {
    slug: "ai-in-finance",
    title: "AI in Finance",
    titleVi: "AI trong Tài chính",
    description: "Ứng dụng AI trong phát hiện gian lận, phân tích rủi ro và giao dịch tự động",
    category: "applied-ai",
    tags: ["fraud-detection", "risk", "trading"],
    difficulty: "beginner",
    relatedSlugs: ["decision-trees", "gradient-boosting", "sentiment-analysis"],
    vizType: "interactive",
    tocSections: [{ id: "explanation", labelVi: "Giải thích" }],
  },
  {
    slug: "ai-in-agriculture",
    title: "AI in Agriculture",
    titleVi: "AI trong Nông nghiệp",
    description: "Ứng dụng AI trong phát hiện sâu bệnh, dự báo mùa vụ và nông nghiệp chính xác tại Việt Nam",
    category: "applied-ai",
    tags: ["crop", "pest-detection", "precision-farming"],
    difficulty: "beginner",
    relatedSlugs: ["image-classification", "object-detection", "edge-ai"],
    vizType: "interactive",
    tocSections: [{ id: "explanation", labelVi: "Giải thích" }],
  },
  {
    slug: "ai-in-education",
    title: "AI in Education",
    titleVi: "AI trong Giáo dục",
    description: "Ứng dụng AI trong cá nhân hoá học tập, chấm bài tự động và trợ lý giảng dạy thông minh",
    category: "applied-ai",
    tags: ["personalization", "tutoring", "assessment"],
    difficulty: "beginner",
    relatedSlugs: ["llm-overview", "rag", "recommendation-systems"],
    vizType: "interactive",
    tocSections: [{ id: "explanation", labelVi: "Giải thích" }],
  },
  {
    slug: "getting-started-with-ai",
    title: "Getting Started with AI",
    titleVi: "Bắt đầu sử dụng AI",
    description:
      "Hướng dẫn tạo tài khoản, cuộc hội thoại đầu tiên, và mẹo nhận kết quả tốt trong 5 phút.",
    category: "applied-ai",
    tags: ["beginner", "practical", "office", "getting-started"],
    difficulty: "beginner",
    relatedSlugs: ["llm-overview", "prompt-engineering", "ai-tool-evaluation"],
    vizType: "interactive",
  },
  {
    slug: "ai-for-writing",
    title: "AI for Writing",
    titleVi: "AI hỗ trợ viết lách",
    description:
      "Dùng AI để viết email, báo cáo, bài thuyết trình, và tóm tắt cuộc họp nhanh hơn.",
    category: "applied-ai",
    tags: ["writing", "email", "reports", "practical", "office"],
    difficulty: "beginner",
    relatedSlugs: [
      "prompt-engineering",
      "getting-started-with-ai",
      "ai-tool-evaluation",
    ],
    vizType: "interactive",
  },
  {
    slug: "ai-for-data-analysis",
    title: "AI for Data Analysis",
    titleVi: "AI phân tích dữ liệu",
    description:
      "Dùng AI để phân tích bảng tính, tạo biểu đồ, viết SQL, và tìm insight từ dữ liệu.",
    category: "applied-ai",
    tags: ["data-analysis", "spreadsheet", "sql", "practical", "office"],
    difficulty: "beginner",
    relatedSlugs: [
      "prompt-engineering",
      "ai-for-writing",
      "getting-started-with-ai",
    ],
    vizType: "interactive",
  },
  {
    slug: "ai-tool-evaluation",
    title: "AI Tool Evaluation",
    titleVi: "So sánh và chọn AI tool",
    description:
      "So sánh ChatGPT, Claude, Gemini, Copilot — chọn công cụ phù hợp cho nhu cầu công việc.",
    category: "applied-ai",
    tags: ["comparison", "evaluation", "tools", "practical", "office"],
    difficulty: "beginner",
    relatedSlugs: [
      "getting-started-with-ai",
      "prompt-engineering",
      "ai-for-writing",
    ],
    vizType: "interactive",
  },
  {
    slug: "ai-privacy-security",
    title: "AI Privacy & Security",
    titleVi: "Bảo mật khi dùng AI",
    description:
      "Những gì KHÔNG NÊN đưa vào AI tool, chính sách dữ liệu công ty, và cách bảo vệ thông tin cá nhân.",
    category: "ai-safety",
    tags: ["privacy", "security", "data-protection", "practical", "office"],
    difficulty: "beginner",
    relatedSlugs: ["guardrails", "ai-governance", "bias-fairness"],
    vizType: "interactive",
  },

  // ═══════════════════════════════════════════════════════
  // Category 17: math-foundations (4 topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "linear-algebra-for-ml",
    title: "Linear Algebra for ML",
    titleVi: "Đại số tuyến tính cho ML",
    description: "Vector, ma trận, phép nhân ma trận và trị riêng — nền tảng toán học cho mọi mô hình AI",
    category: "math-foundations",
    tags: ["vectors", "matrices", "eigenvalues"],
    difficulty: "beginner",
    relatedSlugs: ["pca", "word-embeddings", "neural-network-overview"],
    vizType: "interactive",
    tocSections: [{ id: "explanation", labelVi: "Giải thích" }],
  },
  {
    slug: "probability-statistics",
    title: "Probability & Statistics",
    titleVi: "Xác suất & Thống kê cơ bản",
    description: "Phân phối xác suất, kỳ vọng, phương sai và định lý Bayes — công cụ cốt lõi cho ML",
    category: "math-foundations",
    tags: ["probability", "distribution", "bayes"],
    difficulty: "beginner",
    relatedSlugs: ["naive-bayes", "logistic-regression", "loss-functions"],
    vizType: "interactive",
    tocSections: [{ id: "explanation", labelVi: "Giải thích" }],
  },
  {
    slug: "calculus-for-backprop",
    title: "Calculus for Backpropagation",
    titleVi: "Giải tích cho lan truyền ngược",
    description: "Đạo hàm, quy tắc chuỗi và gradient — toán học đằng sau quá trình huấn luyện mạng nơ-ron",
    category: "math-foundations",
    tags: ["derivatives", "chain-rule", "gradient"],
    difficulty: "intermediate",
    relatedSlugs: ["backpropagation", "gradient-descent", "loss-functions"],
    vizType: "interactive",
    tocSections: [{ id: "explanation", labelVi: "Giải thích" }],
  },
  {
    slug: "information-theory",
    title: "Information Theory",
    titleVi: "Lý thuyết thông tin",
    description: "Entropy, cross-entropy và KL divergence — đo lường thông tin và so sánh phân phối xác suất",
    category: "math-foundations",
    tags: ["entropy", "kl-divergence", "cross-entropy"],
    difficulty: "intermediate",
    relatedSlugs: ["loss-functions", "probability-statistics", "vae"],
    vizType: "interactive",
    tocSections: [{ id: "explanation", labelVi: "Giải thích" }],
  },

  // ═══════════════════════════════════════════════════════
  // Expand: emerging (5 new topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "agentic-rag",
    title: "Agentic RAG",
    titleVi: "RAG tăng cường với Agent",
    description: "Kết hợp RAG với AI Agent để tự quyết định khi nào truy xuất, xác minh và tổng hợp thông tin",
    category: "emerging",
    tags: ["rag", "agent", "adaptive-retrieval"],
    difficulty: "intermediate",
    relatedSlugs: ["rag", "agent-architecture", "react-framework"],
    vizType: "interactive",
  },
  {
    slug: "model-context-protocol",
    title: "Model Context Protocol (MCP)",
    titleVi: "Giao thức ngữ cảnh mô hình",
    description: "Giao thức chuẩn hoá kết nối LLM với công cụ và nguồn dữ liệu bên ngoài",
    category: "emerging",
    tags: ["protocol", "tools", "standardization"],
    difficulty: "intermediate",
    relatedSlugs: ["function-calling", "orchestration", "agent-architecture"],
    vizType: "interactive",
  },
  {
    slug: "ai-coding-assistants",
    title: "AI Coding Assistants",
    titleVi: "Trợ lý lập trình AI",
    description: "Các công cụ AI hỗ trợ viết code, debug và review — từ autocomplete đến agentic coding",
    category: "emerging",
    tags: ["copilot", "code-generation", "developer-tools"],
    difficulty: "beginner",
    relatedSlugs: ["llm-overview", "function-calling", "agentic-workflows"],
    vizType: "static",
  },
  {
    slug: "structured-outputs",
    title: "Structured Outputs",
    titleVi: "Đầu ra có cấu trúc",
    description: "Kỹ thuật đảm bảo LLM sinh ra JSON, XML hoặc schema cố định thay vì văn bản tự do",
    category: "emerging",
    tags: ["json-mode", "schema", "constrained-decoding"],
    difficulty: "intermediate",
    relatedSlugs: ["function-calling", "prompt-engineering", "guardrails"],
    vizType: "static",
  },
  {
    slug: "computer-use",
    title: "Computer Use",
    titleVi: "AI sử dụng máy tính",
    description: "Khả năng AI Agent điều khiển giao diện người dùng — click, gõ phím, chụp ảnh màn hình",
    category: "emerging",
    tags: ["browser-use", "gui-agent", "automation"],
    difficulty: "intermediate",
    relatedSlugs: ["agent-architecture", "vlm", "agentic-workflows"],
    vizType: "interactive",
  },

  // ═══════════════════════════════════════════════════════
  // Deepen existing categories (8 new topics)
  // ═══════════════════════════════════════════════════════
  {
    slug: "vision-transformer",
    title: "Vision Transformer (ViT)",
    titleVi: "Transformer thị giác",
    description: "Áp dụng kiến trúc Transformer trực tiếp cho hình ảnh bằng cách chia ảnh thành các patch",
    category: "dl-architectures",
    tags: ["vit", "image-patches", "transformer"],
    difficulty: "intermediate",
    relatedSlugs: ["transformer", "cnn", "image-classification", "self-attention"],
    vizType: "interactive",
  },
  {
    slug: "flash-attention",
    title: "Flash Attention",
    titleVi: "Flash Attention",
    description: "Thuật toán tối ưu tính attention nhanh hơn và tiết kiệm bộ nhớ GPU bằng kỹ thuật tiling",
    category: "dl-architectures",
    tags: ["attention", "memory-efficient", "tiling"],
    difficulty: "advanced",
    relatedSlugs: ["self-attention", "multi-head-attention", "gpu-optimization"],
    vizType: "interactive",
  },
  {
    slug: "kv-cache",
    title: "KV Cache",
    titleVi: "Bộ nhớ đệm KV",
    description: "Kỹ thuật lưu trữ key-value đã tính để tránh tính lại khi sinh token mới, tăng tốc suy luận",
    category: "llm-concepts",
    tags: ["inference", "caching", "key-value"],
    difficulty: "intermediate",
    relatedSlugs: ["self-attention", "inference-optimization", "context-window"],
    vizType: "interactive",
  },
  {
    slug: "scaling-laws",
    title: "Scaling Laws",
    titleVi: "Định luật tỷ lệ",
    description: "Quy luật dự đoán hiệu suất mô hình dựa trên kích thước tham số, dữ liệu và compute",
    category: "llm-concepts",
    tags: ["scaling", "compute", "chinchilla"],
    difficulty: "intermediate",
    relatedSlugs: ["llm-overview", "training-optimization", "cost-optimization"],
    vizType: "static",
  },
  {
    slug: "tokenizer-comparison",
    title: "Tokenizer Comparison",
    titleVi: "So sánh Tokenizer",
    description: "So sánh BPE, SentencePiece và WordPiece — ưu nhược điểm và ứng dụng của từng phương pháp",
    category: "nlp",
    tags: ["bpe", "sentencepiece", "wordpiece"],
    difficulty: "intermediate",
    relatedSlugs: ["tokenization", "bert", "gpt"],
    vizType: "interactive",
  },
  {
    slug: "ai-watermarking",
    title: "AI Watermarking",
    titleVi: "Đánh dấu nội dung AI",
    description: "Kỹ thuật nhúng dấu hiệu ẩn vào nội dung do AI tạo ra để xác minh nguồn gốc",
    category: "ai-safety",
    tags: ["watermark", "detection", "provenance"],
    difficulty: "intermediate",
    relatedSlugs: ["guardrails", "ai-governance", "text-to-image"],
    vizType: "interactive",
  },
  {
    slug: "deepfake-detection",
    title: "Deepfake Detection",
    titleVi: "Phát hiện Deepfake",
    description: "Các phương pháp phát hiện video và hình ảnh giả mạo được tạo bởi AI",
    category: "ai-safety",
    tags: ["deepfake", "forensics", "detection"],
    difficulty: "intermediate",
    relatedSlugs: ["gan", "adversarial-robustness", "ai-watermarking"],
    vizType: "interactive",
  },
  {
    slug: "data-pipelines",
    title: "Data Pipelines",
    titleVi: "Đường ống dữ liệu",
    description: "Thiết kế quy trình tự động thu thập, xử lý và chuẩn bị dữ liệu cho huấn luyện mô hình AI",
    category: "infrastructure",
    tags: ["etl", "automation", "data-flow"],
    difficulty: "intermediate",
    relatedSlugs: ["data-preprocessing", "mlops", "feature-engineering"],
    vizType: "static",
  },
  {
    slug: "k-means-in-music-recs",
    title: "K-Means in Music Recommendations",
    titleVi: "K-Means trong Gợi ý Nhạc",
    description:
      "Cách Spotify dùng phân cụm vector để tạo Discover Weekly cho hàng trăm triệu người dùng",
    category: "classic-ml",
    tags: ["clustering", "recommendation", "application"],
    difficulty: "beginner",
    relatedSlugs: ["k-means"],
    vizType: "static",
    applicationOf: "k-means",
    featuredApp: {
      name: "Spotify",
      productFeature: "Discover Weekly",
      company: "Spotify AB",
      countryOrigin: "SE",
    },
    sources: [
      {
        title:
          "What Made Discover Weekly One of Our Most Successful Feature Launches to Date?",
        publisher: "Spotify Engineering",
        url: "https://engineering.atspotify.com/2015/11/what-made-discover-weekly-one-of-our-most-successful-feature-launches-to-date",
        date: "2015-11",
        kind: "engineering-blog",
      },
      {
        title: "From Idea to Execution: Spotify's Discover Weekly",
        publisher: "Chris Johnson & Edward Newett, DataEngConf NYC 2015",
        url: "https://www.slideshare.net/MrChrisJohnson/from-idea-to-execution-spotifys-discover-weekly",
        date: "2015-11",
        kind: "keynote",
      },
      {
        title: "Logistic Matrix Factorization for Implicit Feedback Data",
        publisher: "Chris Johnson, Spotify — NIPS 2014 Workshop",
        url: "https://research.atspotify.com/publications/logistic-matrix-factorization-for-implicit-feedback-data",
        date: "2014-12",
        kind: "paper",
      },
      {
        title:
          "Introducing Voyager: Spotify's New Nearest-Neighbor Search Library",
        publisher: "Spotify Engineering",
        url: "https://engineering.atspotify.com/2023/10/introducing-voyager-spotifys-new-nearest-neighbor-search-library",
        date: "2023-10",
        kind: "engineering-blog",
      },
      {
        title: "Recommending Music on Spotify with Deep Learning",
        publisher: "Sander Dieleman (Spotify internship)",
        url: "https://sander.ai/2014/08/05/spotify-cnns.html",
        date: "2014-08",
        kind: "engineering-blog",
      },
      {
        title: "How to Break Free of Spotify's Algorithm",
        publisher: "MIT Technology Review",
        url: "https://www.technologyreview.com/2024/08/16/1096276/spotify-algorithms-music-discovery-ux/",
        date: "2024-08",
        kind: "news",
      },
      {
        title:
          "How Fans Discover Your Music on Spotify — Made to Be Found",
        publisher: "Spotify for Artists",
        url: "https://artists.spotify.com/en/blog/how-fans-discover-music-on-spotify-playlists-made-to-be-found",
        date: "2022-03",
        kind: "documentation",
      },
    ],
    tocSections: [
      { id: "hero", labelVi: "Công ty nào?" },
      { id: "problem", labelVi: "Vấn đề" },
      { id: "mechanism", labelVi: "Cách giải quyết" },
      { id: "metrics", labelVi: "Con số thật" },
      { id: "counterfactual", labelVi: "Nếu không có" },
    ],
  },
  {
    slug: "backpropagation-in-translation",
    title: "Backpropagation in Translation",
    titleVi: "Lan truyền ngược trong Dịch thuật",
    description:
      "Cách Google Translate dùng lan truyền ngược để huấn luyện mạng nơ-ron sâu, cắt giảm 60% lỗi dịch",
    category: "neural-fundamentals",
    tags: ["backpropagation", "translation", "application"],
    difficulty: "beginner",
    relatedSlugs: ["backpropagation"],
    vizType: "static",
    applicationOf: "backpropagation",
    featuredApp: {
      name: "Google Translate",
      productFeature: "Neural Machine Translation",
      company: "Google LLC",
      countryOrigin: "US",
    },
    sources: [
      {
        title:
          "Google's Neural Machine Translation System: Bridging the Gap between Human and Machine Translation",
        publisher: "arXiv (Google Research)",
        url: "https://arxiv.org/abs/1609.08144",
        date: "2016-09",
        kind: "paper",
      },
      {
        title:
          "A Neural Network for Machine Translation, at Production Scale",
        publisher: "Google Research Blog",
        url: "https://research.google/blog/a-neural-network-for-machine-translation-at-production-scale/",
        date: "2016-09",
        kind: "engineering-blog",
      },
      {
        title: "Recent Advances in Google Translate",
        publisher: "Google Research Blog",
        url: "https://research.google/blog/recent-advances-in-google-translate/",
        date: "2020-06",
        kind: "engineering-blog",
      },
      {
        title: "Attention Is All You Need",
        publisher: "arXiv (Google Brain / NeurIPS 2017)",
        url: "https://arxiv.org/abs/1706.03762",
        date: "2017-06",
        kind: "paper",
      },
    ],
    tocSections: [
      { id: "hero", labelVi: "Công ty nào?" },
      { id: "problem", labelVi: "Vấn đề" },
      { id: "mechanism", labelVi: "Cách giải quyết" },
      { id: "metrics", labelVi: "Con số thật" },
      { id: "counterfactual", labelVi: "Nếu không có" },
    ],
  },
];

// ─────────────────────────────────────────────────────────
// Derived data structures & utility functions
// ─────────────────────────────────────────────────────────

/** Lookup map: slug → TopicMeta */
export const topicMap: Record<string, TopicMeta> = Object.fromEntries(
  topicList.map((t) => [t.slug, t])
);

/** Look up a single topic by slug. Returns undefined if not found. */
export function getTopicBySlug(slug: string): TopicMeta | undefined {
  return topicMap[slug];
}

/** Get all topic metadata as an array. */
export function getAllTopics(): TopicMeta[] {
  return topicList;
}

/** Get all topics belonging to a specific category. */
export function getTopicsByCategory(categorySlug: string): TopicMeta[] {
  return topicList.filter((t) => t.category === categorySlug);
}
