// Server Component — importing topic modules here statically preserves
// code-splitting (via next/dynamic) while letting Next.js SSR each topic
// into the initial HTML. Do NOT add "use client" to this file.

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import type { TopicMeta } from "@/lib/types";
import TopicLayout from "@/components/topic/TopicLayout";

// Static component registry — one entry per topic .tsx file under src/topics/.
// Using literal import paths (not a template string) so Turbopack/webpack can
// statically resolve each chunk and SSR the correct module on the server. A
// previous template-literal dynamic import caused BAILOUT_TO_CLIENT_SIDE_RENDERING
// on every /topics/<slug> route, shipping a skeleton-only HTML to crawlers.
//
// IMPORTANT: when adding a new topic file, add a matching entry here AND an entry
// in src/topics/registry.ts. Keep this list alphabetized.
const topicComponents: Record<string, ComponentType> = {
  "activation-functions": dynamic(() => import("@/topics/activation-functions")),
  "activation-functions-in-alphago": dynamic(() => import("@/topics/activation-functions-in-alphago")),
  "actor-critic": dynamic(() => import("@/topics/actor-critic")),
  "adversarial-robustness": dynamic(() => import("@/topics/adversarial-robustness")),
  "agent-architecture": dynamic(() => import("@/topics/agent-architecture")),
  "agent-evaluation": dynamic(() => import("@/topics/agent-evaluation")),
  "agentic-rag": dynamic(() => import("@/topics/agentic-rag")),
  "agentic-workflows": dynamic(() => import("@/topics/agentic-workflows")),
  "ai-coding-assistants": dynamic(() => import("@/topics/ai-coding-assistants")),
  "ai-for-data-analysis": dynamic(() => import("@/topics/ai-for-data-analysis")),
  "ai-for-science": dynamic(() => import("@/topics/ai-for-science")),
  "ai-for-writing": dynamic(() => import("@/topics/ai-for-writing")),
  "ai-governance": dynamic(() => import("@/topics/ai-governance")),
  "ai-governance-in-enterprise": dynamic(() => import("@/topics/ai-governance-in-enterprise")),
  "ai-in-agriculture": dynamic(() => import("@/topics/ai-in-agriculture")),
  "ai-in-education": dynamic(() => import("@/topics/ai-in-education")),
  "ai-in-finance": dynamic(() => import("@/topics/ai-in-finance")),
  "ai-in-healthcare": dynamic(() => import("@/topics/ai-in-healthcare")),
  "ai-privacy-security": dynamic(() => import("@/topics/ai-privacy-security")),
  "ai-tool-evaluation": dynamic(() => import("@/topics/ai-tool-evaluation")),
  "ai-watermarking": dynamic(() => import("@/topics/ai-watermarking")),
  "alignment": dynamic(() => import("@/topics/alignment")),
  "anchor-boxes": dynamic(() => import("@/topics/anchor-boxes")),
  "attention-mechanism": dynamic(() => import("@/topics/attention-mechanism")),
  "autoencoder": dynamic(() => import("@/topics/autoencoder")),
  "backpropagation": dynamic(() => import("@/topics/backpropagation")),
  "backpropagation-in-translation": dynamic(() => import("@/topics/backpropagation-in-translation")),
  "bag-of-words": dynamic(() => import("@/topics/bag-of-words")),
  "batch-normalization": dynamic(() => import("@/topics/batch-normalization")),
  "beam-search": dynamic(() => import("@/topics/beam-search")),
  "bert": dynamic(() => import("@/topics/bert")),
  "bias-fairness": dynamic(() => import("@/topics/bias-fairness")),
  "bias-fairness-in-hiring": dynamic(() => import("@/topics/bias-fairness-in-hiring")),
  "bias-variance": dynamic(() => import("@/topics/bias-variance")),
  "bias-variance-in-netflix-prize": dynamic(() => import("@/topics/bias-variance-in-netflix-prize")),
  "bm25": dynamic(() => import("@/topics/bm25")),
  "calculus-for-backprop": dynamic(() => import("@/topics/calculus-for-backprop")),
  "calculus-for-backprop-in-model-training": dynamic(() => import("@/topics/calculus-for-backprop-in-model-training")),
  "canary-releases-llm": dynamic(() => import("@/topics/canary-releases-llm")),
  "chain-of-thought": dynamic(() => import("@/topics/chain-of-thought")),
  "chain-of-thought-in-reasoning-models": dynamic(() => import("@/topics/chain-of-thought-in-reasoning-models")),
  "chunking": dynamic(() => import("@/topics/chunking")),
  "clip": dynamic(() => import("@/topics/clip")),
  "cnn": dynamic(() => import("@/topics/cnn")),
  "color-spaces": dynamic(() => import("@/topics/color-spaces")),
  "computer-use": dynamic(() => import("@/topics/computer-use")),
  "confusion-matrix": dynamic(() => import("@/topics/confusion-matrix")),
  "confusion-matrix-in-medical-testing": dynamic(() => import("@/topics/confusion-matrix-in-medical-testing")),
  "constitutional-ai": dynamic(() => import("@/topics/constitutional-ai")),
  "containerization": dynamic(() => import("@/topics/containerization")),
  "context-window": dynamic(() => import("@/topics/context-window")),
  "context-window-in-long-documents": dynamic(() => import("@/topics/context-window-in-long-documents")),
  "convolution": dynamic(() => import("@/topics/convolution")),
  "cost-latency-tokens": dynamic(() => import("@/topics/cost-latency-tokens")),
  "cost-optimization": dynamic(() => import("@/topics/cost-optimization")),
  "cross-validation": dynamic(() => import("@/topics/cross-validation")),
  "cross-validation-in-kaggle": dynamic(() => import("@/topics/cross-validation-in-kaggle")),
  "data-and-datasets": dynamic(() => import("@/topics/data-and-datasets")),
  "data-augmentation": dynamic(() => import("@/topics/data-augmentation")),
  "data-pipelines": dynamic(() => import("@/topics/data-pipelines")),
  "data-preprocessing": dynamic(() => import("@/topics/data-preprocessing")),
  "data-preprocessing-in-uber-eta": dynamic(() => import("@/topics/data-preprocessing-in-uber-eta")),
  "dbscan": dynamic(() => import("@/topics/dbscan")),
  "decision-trees": dynamic(() => import("@/topics/decision-trees")),
  "decision-trees-in-loan-scoring": dynamic(() => import("@/topics/decision-trees-in-loan-scoring")),
  "deep-q-network": dynamic(() => import("@/topics/deep-q-network")),
  "deepfake-detection": dynamic(() => import("@/topics/deepfake-detection")),
  "diffusion-models": dynamic(() => import("@/topics/diffusion-models")),
  "dimensionality-curse": dynamic(() => import("@/topics/dimensionality-curse")),
  "distillation": dynamic(() => import("@/topics/distillation")),
  "dpo": dynamic(() => import("@/topics/dpo")),
  "edge-ai": dynamic(() => import("@/topics/edge-ai")),
  "eigendecomposition-pca": dynamic(() => import("@/topics/eigendecomposition-pca")),
  "embedding-model": dynamic(() => import("@/topics/embedding-model")),
  "end-to-end-ml-project": dynamic(() => import("@/topics/end-to-end-ml-project")),
  "ensemble-methods": dynamic(() => import("@/topics/ensemble-methods")),
  "epochs-batches": dynamic(() => import("@/topics/epochs-batches")),
  "epochs-batches-in-gpt-training": dynamic(() => import("@/topics/epochs-batches-in-gpt-training")),
  "explainability": dynamic(() => import("@/topics/explainability")),
  "explainability-in-credit-decisions": dynamic(() => import("@/topics/explainability-in-credit-decisions")),
  "faiss": dynamic(() => import("@/topics/faiss")),
  "feature-engineering": dynamic(() => import("@/topics/feature-engineering")),
  "feature-engineering-in-fraud-detection": dynamic(() => import("@/topics/feature-engineering-in-fraud-detection")),
  "feature-extraction-cnn": dynamic(() => import("@/topics/feature-extraction-cnn")),
  "fine-tuning": dynamic(() => import("@/topics/fine-tuning")),
  "fine-tuning-vs-prompting": dynamic(() => import("@/topics/fine-tuning-vs-prompting")),
  "flash-attention": dynamic(() => import("@/topics/flash-attention")),
  "forward-propagation": dynamic(() => import("@/topics/forward-propagation")),
  "forward-propagation-in-chat-response": dynamic(() => import("@/topics/forward-propagation-in-chat-response")),
  "function-calling": dynamic(() => import("@/topics/function-calling")),
  "gan": dynamic(() => import("@/topics/gan")),
  "getting-started-with-ai": dynamic(() => import("@/topics/getting-started-with-ai")),
  "glove": dynamic(() => import("@/topics/glove")),
  "gpt": dynamic(() => import("@/topics/gpt")),
  "gpu-optimization": dynamic(() => import("@/topics/gpu-optimization")),
  "gradient-boosting": dynamic(() => import("@/topics/gradient-boosting")),
  "gradient-descent": dynamic(() => import("@/topics/gradient-descent")),
  "gradient-descent-in-training": dynamic(() => import("@/topics/gradient-descent-in-training")),
  "grpo": dynamic(() => import("@/topics/grpo")),
  "gru": dynamic(() => import("@/topics/gru")),
  "guardrails": dynamic(() => import("@/topics/guardrails")),
  "guardrails-in-chat-assistants": dynamic(() => import("@/topics/guardrails-in-chat-assistants")),
  "hallucination": dynamic(() => import("@/topics/hallucination")),
  "hallucination-in-legal-research": dynamic(() => import("@/topics/hallucination-in-legal-research")),
  "hybrid-search": dynamic(() => import("@/topics/hybrid-search")),
  "hyperparameter-tuning": dynamic(() => import("@/topics/hyperparameter-tuning")),
  "image-classification": dynamic(() => import("@/topics/image-classification")),
  "image-kernels": dynamic(() => import("@/topics/image-kernels")),
  "in-context-learning": dynamic(() => import("@/topics/in-context-learning")),
  "in-context-learning-in-chatbots": dynamic(() => import("@/topics/in-context-learning-in-chatbots")),
  "inference-optimization": dynamic(() => import("@/topics/inference-optimization")),
  "information-theory": dynamic(() => import("@/topics/information-theory")),
  "information-theory-in-compression": dynamic(() => import("@/topics/information-theory-in-compression")),
  "instance-segmentation": dynamic(() => import("@/topics/instance-segmentation")),
  "iou": dynamic(() => import("@/topics/iou")),
  "jupyter-colab-workflow": dynamic(() => import("@/topics/jupyter-colab-workflow")),
  "k-means": dynamic(() => import("@/topics/k-means")),
  "k-means-in-music-recs": dynamic(() => import("@/topics/k-means-in-music-recs")),
  "knn": dynamic(() => import("@/topics/knn")),
  "knn-in-symptom-checker": dynamic(() => import("@/topics/knn-in-symptom-checker")),
  "kv-cache": dynamic(() => import("@/topics/kv-cache")),
  "learning-rate": dynamic(() => import("@/topics/learning-rate")),
  "linear-regression": dynamic(() => import("@/topics/linear-regression")),
  "linear-regression-in-housing": dynamic(() => import("@/topics/linear-regression-in-housing")),
  "llm-evaluation": dynamic(() => import("@/topics/llm-evaluation")),
  "llm-overview": dynamic(() => import("@/topics/llm-overview")),
  "llm-overview-in-chat-assistants": dynamic(() => import("@/topics/llm-overview-in-chat-assistants")),
  "logistic-regression": dynamic(() => import("@/topics/logistic-regression")),
  "logistic-regression-in-spam-filter": dynamic(() => import("@/topics/logistic-regression-in-spam-filter")),
  "long-context": dynamic(() => import("@/topics/long-context")),
  "lora": dynamic(() => import("@/topics/lora")),
  "loss-functions": dynamic(() => import("@/topics/loss-functions")),
  "loss-functions-in-recommendation": dynamic(() => import("@/topics/loss-functions-in-recommendation")),
  "lstm": dynamic(() => import("@/topics/lstm")),
  "math-readiness": dynamic(() => import("@/topics/math-readiness")),
  "memory-systems": dynamic(() => import("@/topics/memory-systems")),
  "mixed-precision": dynamic(() => import("@/topics/mixed-precision")),
  "mlops": dynamic(() => import("@/topics/mlops")),
  "mlp": dynamic(() => import("@/topics/mlp")),
  "mlp-in-credit-scoring": dynamic(() => import("@/topics/mlp-in-credit-scoring")),
  "model-context-protocol": dynamic(() => import("@/topics/model-context-protocol")),
  "model-evaluation-selection": dynamic(() => import("@/topics/model-evaluation-selection")),
  "model-evaluation-selection-in-kaggle": dynamic(() => import("@/topics/model-evaluation-selection-in-kaggle")),
  "model-serving": dynamic(() => import("@/topics/model-serving")),
  "moe": dynamic(() => import("@/topics/moe")),
  "monitoring": dynamic(() => import("@/topics/monitoring")),
  "multi-agent": dynamic(() => import("@/topics/multi-agent")),
  "multi-armed-bandit": dynamic(() => import("@/topics/multi-armed-bandit")),
  "multi-head-attention": dynamic(() => import("@/topics/multi-head-attention")),
  "naive-bayes": dynamic(() => import("@/topics/naive-bayes")),
  "naive-bayes-in-email-classification": dynamic(() => import("@/topics/naive-bayes-in-email-classification")),
  "ner": dynamic(() => import("@/topics/ner")),
  "nerf": dynamic(() => import("@/topics/nerf")),
  "neural-network-overview": dynamic(() => import("@/topics/neural-network-overview")),
  "neural-network-overview-in-voice-assistants": dynamic(() => import("@/topics/neural-network-overview-in-voice-assistants")),
  "nms": dynamic(() => import("@/topics/nms")),
  "object-detection": dynamic(() => import("@/topics/object-detection")),
  "observability-for-ai": dynamic(() => import("@/topics/observability-for-ai")),
  "optical-flow": dynamic(() => import("@/topics/optical-flow")),
  "optimizers": dynamic(() => import("@/topics/optimizers")),
  "orchestration": dynamic(() => import("@/topics/orchestration")),
  "overfitting-underfitting": dynamic(() => import("@/topics/overfitting-underfitting")),
  "overfitting-underfitting-in-compas": dynamic(() => import("@/topics/overfitting-underfitting-in-compas")),
  "panoptic-segmentation": dynamic(() => import("@/topics/panoptic-segmentation")),
  "pca": dynamic(() => import("@/topics/pca")),
  "perceptron": dynamic(() => import("@/topics/perceptron")),
  "perceptron-in-image-classification": dynamic(() => import("@/topics/perceptron-in-image-classification")),
  "perplexity-metric": dynamic(() => import("@/topics/perplexity-metric")),
  "planning": dynamic(() => import("@/topics/planning")),
  "policy-gradient": dynamic(() => import("@/topics/policy-gradient")),
  "polynomial-regression": dynamic(() => import("@/topics/polynomial-regression")),
  "pooling": dynamic(() => import("@/topics/pooling")),
  "positional-encoding": dynamic(() => import("@/topics/positional-encoding")),
  "probability-statistics": dynamic(() => import("@/topics/probability-statistics")),
  "probability-statistics-in-spam-filter": dynamic(() => import("@/topics/probability-statistics-in-spam-filter")),
  "prompt-engineering": dynamic(() => import("@/topics/prompt-engineering")),
  "prompt-engineering-in-writing-tools": dynamic(() => import("@/topics/prompt-engineering-in-writing-tools")),
  "prompt-injection-defense": dynamic(() => import("@/topics/prompt-injection-defense")),
  "pruning": dynamic(() => import("@/topics/pruning")),
  "python-for-ml": dynamic(() => import("@/topics/python-for-ml")),
  "q-learning": dynamic(() => import("@/topics/q-learning")),
  "qlora": dynamic(() => import("@/topics/qlora")),
  "quantization": dynamic(() => import("@/topics/quantization")),
  "rag": dynamic(() => import("@/topics/rag")),
  "rag-evaluation": dynamic(() => import("@/topics/rag-evaluation")),
  "random-forests": dynamic(() => import("@/topics/random-forests")),
  "re-ranking": dynamic(() => import("@/topics/re-ranking")),
  "react-framework": dynamic(() => import("@/topics/react-framework")),
  "reasoning-models": dynamic(() => import("@/topics/reasoning-models")),
  "recommendation-systems": dynamic(() => import("@/topics/recommendation-systems")),
  "recommendation-systems-in-shopping": dynamic(() => import("@/topics/recommendation-systems-in-shopping")),
  "red-teaming": dynamic(() => import("@/topics/red-teaming")),
  "regularization": dynamic(() => import("@/topics/regularization")),
  "residual-connections": dynamic(() => import("@/topics/residual-connections")),
  "rlhf": dynamic(() => import("@/topics/rlhf")),
  "rnn": dynamic(() => import("@/topics/rnn")),
  "roc-auc": dynamic(() => import("@/topics/roc-auc")),
  "scaling-laws": dynamic(() => import("@/topics/scaling-laws")),
  "self-attention": dynamic(() => import("@/topics/self-attention")),
  "semantic-search": dynamic(() => import("@/topics/semantic-search")),
  "semantic-segmentation": dynamic(() => import("@/topics/semantic-segmentation")),
  "sentiment-analysis": dynamic(() => import("@/topics/sentiment-analysis")),
  "sentiment-analysis-in-brand-monitoring": dynamic(() => import("@/topics/sentiment-analysis-in-brand-monitoring")),
  "seq2seq": dynamic(() => import("@/topics/seq2seq")),
  "sgd": dynamic(() => import("@/topics/sgd")),
  "small-language-models": dynamic(() => import("@/topics/small-language-models")),
  "speech-recognition": dynamic(() => import("@/topics/speech-recognition")),
  "state-space-models": dynamic(() => import("@/topics/state-space-models")),
  "structured-outputs": dynamic(() => import("@/topics/structured-outputs")),
  "style-transfer": dynamic(() => import("@/topics/style-transfer")),
  "supervised-unsupervised-rl": dynamic(() => import("@/topics/supervised-unsupervised-rl")),
  "supervised-unsupervised-rl-in-netflix": dynamic(() => import("@/topics/supervised-unsupervised-rl-in-netflix")),
  "svm": dynamic(() => import("@/topics/svm")),
  "synthetic-data": dynamic(() => import("@/topics/synthetic-data")),
  "t-sne": dynamic(() => import("@/topics/t-sne")),
  "temperature": dynamic(() => import("@/topics/temperature")),
  "temperature-in-creative-writing": dynamic(() => import("@/topics/temperature-in-creative-writing")),
  "test-time-compute": dynamic(() => import("@/topics/test-time-compute")),
  "text-classification": dynamic(() => import("@/topics/text-classification")),
  "text-classification-in-support-routing": dynamic(() => import("@/topics/text-classification-in-support-routing")),
  "text-to-image": dynamic(() => import("@/topics/text-to-image")),
  "text-to-video": dynamic(() => import("@/topics/text-to-video")),
  "tf-idf": dynamic(() => import("@/topics/tf-idf")),
  "tlm": dynamic(() => import("@/topics/tlm")),
  "tokenization": dynamic(() => import("@/topics/tokenization")),
  "tokenizer-comparison": dynamic(() => import("@/topics/tokenizer-comparison")),
  "top-k-top-p": dynamic(() => import("@/topics/top-k-top-p")),
  "train-val-test": dynamic(() => import("@/topics/train-val-test")),
  "train-val-test-in-youtube": dynamic(() => import("@/topics/train-val-test-in-youtube")),
  "transfer-learning": dynamic(() => import("@/topics/transfer-learning")),
  "transformer": dynamic(() => import("@/topics/transformer")),
  "tts": dynamic(() => import("@/topics/tts")),
  "u-net": dynamic(() => import("@/topics/u-net")),
  "unified-multimodal": dynamic(() => import("@/topics/unified-multimodal")),
  "vae": dynamic(() => import("@/topics/vae")),
  "vanishing-exploding-gradients": dynamic(() => import("@/topics/vanishing-exploding-gradients")),
  "vector-databases": dynamic(() => import("@/topics/vector-databases")),
  "vectors-and-matrices": dynamic(() => import("@/topics/vectors-and-matrices")),
  "vectors-and-matrices-in-photo-search": dynamic(() => import("@/topics/vectors-and-matrices-in-photo-search")),
  "vision-transformer": dynamic(() => import("@/topics/vision-transformer")),
  "vlm": dynamic(() => import("@/topics/vlm")),
  "weight-initialization": dynamic(() => import("@/topics/weight-initialization")),
  "what-is-ml": dynamic(() => import("@/topics/what-is-ml")),
  "word-embeddings": dynamic(() => import("@/topics/word-embeddings")),
  "word2vec": dynamic(() => import("@/topics/word2vec")),
  "world-models": dynamic(() => import("@/topics/world-models")),
};

interface TopicLoaderProps {
  meta: TopicMeta;
}

export default function TopicLoader({ meta }: TopicLoaderProps) {
  const TopicContent = topicComponents[meta.slug];

  return (
    <TopicLayout meta={meta}>
      {TopicContent ? <TopicContent /> : null}
    </TopicLayout>
  );
}
